/**
 * @fileoverview Genshin Impact character database
 * @module adapters/game-definitions/genshin-impact/characters
 *
 * Per-character base stats, element, weapon, and icon path. Icons live under
 * `icons/characters/<id>.png` relative to this game package.
 */

import type { ElementType, WeaponType, CharacterSkill } from '@shared/types/game-definition';

export interface GICharacter {
    id: string;
    name: string;
    element: ElementType;
    weapon: WeaponType;
    rarity: number;
    baseAtk: number;
    baseHp: number;
    baseDef: number;
    baseCritRate: number;
    baseCritDmg: number;
    baseEnergyRegen: number;
    baseElementalMastery?: number;
    icon: string;
    /** Per-character skills (precise). Omitted → falls back to game-wide actions. */
    skills?: CharacterSkill[];
}

export const CHARACTERS: GICharacter[] = [
    { id: 'traveler-anemo', name: 'Traveler (Anemo)', element: 'Anemo', weapon: 'Sword', rarity: 5, baseAtk: 780, baseHp: 10875, baseDef: 685, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/traveler-anemo.png' },
    { id: 'traveler-geo', name: 'Traveler (Geo)', element: 'Geo', weapon: 'Sword', rarity: 5, baseAtk: 780, baseHp: 10875, baseDef: 685, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/traveler-geo.png' },
    { id: 'traveler-electro', name: 'Traveler (Electro)', element: 'Electro', weapon: 'Sword', rarity: 5, baseAtk: 780, baseHp: 10875, baseDef: 685, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/traveler-electro.png' },
    { id: 'traveler-dendro', name: 'Traveler (Dendro)', element: 'Dendro', weapon: 'Sword', rarity: 5, baseAtk: 780, baseHp: 10875, baseDef: 685, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/traveler-dendro.png' },
    { id: 'traveler-hydro', name: 'Traveler (Hydro)', element: 'Hydro', weapon: 'Sword', rarity: 5, baseAtk: 780, baseHp: 10875, baseDef: 685, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/traveler-hydro.png' },
    { id: 'amber', name: 'Amber', element: 'Pyro', weapon: 'Bow', rarity: 4, baseAtk: 723, baseHp: 9461, baseDef: 600, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/amber.png' },
    { id: 'kaeya', name: 'Kaeya', element: 'Cryo', weapon: 'Sword', rarity: 4, baseAtk: 733, baseHp: 11636, baseDef: 631, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/kaeya.png' },
    { id: 'lisa', name: 'Lisa', element: 'Electro', weapon: 'Catalyst', rarity: 4, baseAtk: 730, baseHp: 9570, baseDef: 573, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/lisa.png' },
    { id: 'barbara', name: 'Barbara', element: 'Hydro', weapon: 'Catalyst', rarity: 4, baseAtk: 717, baseHp: 9787, baseDef: 618, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/barbara.png' },
    { id: 'razor', name: 'Razor', element: 'Electro', weapon: 'Claymore', rarity: 4, baseAtk: 741, baseHp: 11962, baseDef: 640, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/razor.png' },
    { id: 'bennett', name: 'Bennett', element: 'Pyro', weapon: 'Sword', rarity: 4, baseAtk: 713, baseHp: 12397, baseDef: 636, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/bennett.png' },
    { id: 'noelle', name: 'Noelle', element: 'Geo', weapon: 'Claymore', rarity: 4, baseAtk: 727, baseHp: 12071, baseDef: 799, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/noelle.png' },
    { id: 'fischl', name: 'Fischl', element: 'Electro', weapon: 'Bow', rarity: 4, baseAtk: 745, baseHp: 9189, baseDef: 594, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/fischl.png' },
    { id: 'sucrose', name: 'Sucrose', element: 'Anemo', weapon: 'Catalyst', rarity: 4, baseAtk: 724, baseHp: 9244, baseDef: 703, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/sucrose.png' },
    { id: 'beidou', name: 'Beidou', element: 'Electro', weapon: 'Claymore', rarity: 4, baseAtk: 740, baseHp: 11046, baseDef: 621, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/beidou.png' },
    { id: 'ningguang', name: 'Ningguang', element: 'Geo', weapon: 'Catalyst', rarity: 4, baseAtk: 736, baseHp: 9787, baseDef: 573, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/ningguang.png' },
    { id: 'xiangling', name: 'Xiangling', element: 'Pyro', weapon: 'Polearm', rarity: 4, baseAtk: 725, baseHp: 10875, baseDef: 669, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/xiangling.png' },
    { id: 'xingqiu', name: 'Xingqiu', element: 'Hydro', weapon: 'Sword', rarity: 4, baseAtk: 728, baseHp: 10222, baseDef: 758, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/xingqiu.png' },
    { id: 'chongyun', name: 'Chongyun', element: 'Cryo', weapon: 'Claymore', rarity: 4, baseAtk: 739, baseHp: 10984, baseDef: 648, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/chongyun.png' },
    { id: 'jean', name: 'Jean', element: 'Anemo', weapon: 'Sword', rarity: 5, baseAtk: 765, baseHp: 12858, baseDef: 754, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/jean.png' },
    { id: 'diluc', name: 'Diluc', element: 'Pyro', weapon: 'Claymore', rarity: 5, baseAtk: 805, baseHp: 12981, baseDef: 784, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/diluc.png' },
    { id: 'qiqi', name: 'Qiqi', element: 'Cryo', weapon: 'Sword', rarity: 5, baseAtk: 770, baseHp: 12368, baseDef: 922, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/qiqi.png' },
    { id: 'mona', name: 'Mona', element: 'Hydro', weapon: 'Catalyst', rarity: 5, baseAtk: 786, baseHp: 10409, baseDef: 653, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/mona.png' },
    { id: 'keqing', name: 'Keqing', element: 'Electro', weapon: 'Sword', rarity: 5, baseAtk: 791, baseHp: 13103, baseDef: 799, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/keqing.png' },
    { id: 'venti', name: 'Venti', element: 'Anemo', weapon: 'Bow', rarity: 5, baseAtk: 776, baseHp: 10531, baseDef: 676, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/venti.png' },
    { id: 'klee', name: 'Klee', element: 'Pyro', weapon: 'Catalyst', rarity: 5, baseAtk: 800, baseHp: 10287, baseDef: 615, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/klee.png' },
    { id: 'zhongli', name: 'Zhongli', element: 'Geo', weapon: 'Polearm', rarity: 5, baseAtk: 761, baseHp: 14695, baseDef: 738, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/zhongli.png' },
    { id: 'childe', name: 'Childe (Tartaglia)', element: 'Hydro', weapon: 'Bow', rarity: 5, baseAtk: 794, baseHp: 13103, baseDef: 815, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/childe.png' },
    { id: 'albedo', name: 'Albedo', element: 'Geo', weapon: 'Sword', rarity: 5, baseAtk: 767, baseHp: 13226, baseDef: 876, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/albedo.png' },
    { id: 'ganyu', name: 'Ganyu', element: 'Cryo', weapon: 'Bow', rarity: 5, baseAtk: 783, baseHp: 9797, baseDef: 630, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/ganyu.png' },
    { id: 'xiao', name: 'Xiao', element: 'Anemo', weapon: 'Polearm', rarity: 5, baseAtk: 803, baseHp: 12736, baseDef: 799, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/xiao.png' },
    { id: 'hu_tao', name: 'Hu Tao', element: 'Pyro', weapon: 'Polearm', rarity: 5, baseAtk: 715, baseHp: 15552, baseDef: 876, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/hu_tao.png' },
    { id: 'rosaria', name: 'Rosaria', element: 'Cryo', weapon: 'Polearm', rarity: 4, baseAtk: 742, baseHp: 12289, baseDef: 601, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/rosaria.png' },
    { id: 'eula', name: 'Eula', element: 'Cryo', weapon: 'Claymore', rarity: 5, baseAtk: 789, baseHp: 13226, baseDef: 751, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/eula.png' },
    { id: 'yoimiya', name: 'Yoimiya', element: 'Pyro', weapon: 'Bow', rarity: 5, baseAtk: 785, baseHp: 10164, baseDef: 615, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/yoimiya.png' },
    { id: 'sayu', name: 'Sayu', element: 'Anemo', weapon: 'Claymore', rarity: 4, baseAtk: 736, baseHp: 11854, baseDef: 745, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/sayu.png' },
    { id: 'kazuha', name: 'Kaedehara Kazuha', element: 'Anemo', weapon: 'Sword', rarity: 5, baseAtk: 782, baseHp: 13348, baseDef: 807, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/kazuha.png' },
    { id: 'ayaka', name: 'Kamisato Ayaka', element: 'Cryo', weapon: 'Sword', rarity: 5, baseAtk: 784, baseHp: 12858, baseDef: 784, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/ayaka.png' },
    { id: 'raiden', name: 'Raiden Shogun', element: 'Electro', weapon: 'Polearm', rarity: 5, baseAtk: 788, baseHp: 12907, baseDef: 789, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/raiden.png' },
    { id: 'sara', name: 'Kujou Sara', element: 'Electro', weapon: 'Bow', rarity: 4, baseAtk: 744, baseHp: 9570, baseDef: 628, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/sara.png' },
    { id: 'kokomi', name: 'Sangonomiya Kokomi', element: 'Hydro', weapon: 'Catalyst', rarity: 5, baseAtk: 767, baseHp: 13471, baseDef: 652, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/kokomi.png' },
    { id: 'thoma', name: 'Thoma', element: 'Pyro', weapon: 'Polearm', rarity: 4, baseAtk: 719, baseHp: 11846, baseDef: 733, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/thoma.png' },
    { id: 'gorou', name: 'Gorou', element: 'Geo', weapon: 'Bow', rarity: 4, baseAtk: 738, baseHp: 9570, baseDef: 622, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/gorou.png' },
    { id: 'itto', name: 'Arataki Itto', element: 'Geo', weapon: 'Claymore', rarity: 5, baseAtk: 776, baseHp: 12858, baseDef: 959, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/itto.png' },
    { id: 'shenhe', name: 'Shenhe', element: 'Cryo', weapon: 'Polearm', rarity: 5, baseAtk: 794, baseHp: 12993, baseDef: 771, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/shenhe.png' },
    { id: 'yunjin', name: 'Yunjin', element: 'Geo', weapon: 'Polearm', rarity: 4, baseAtk: 727, baseHp: 10657, baseDef: 799, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/yunjin.png' },
    { id: 'yae_miko', name: 'Yae Miko', element: 'Electro', weapon: 'Catalyst', rarity: 5, baseAtk: 802, baseHp: 10372, baseDef: 569, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/yae_miko.png' },
    { id: 'ayato', name: 'Kamisato Ayato', element: 'Hydro', weapon: 'Sword', rarity: 5, baseAtk: 799, baseHp: 13715, baseDef: 769, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/ayato.png' },
    { id: 'nahida', name: 'Nahida', element: 'Dendro', weapon: 'Catalyst', rarity: 5, baseAtk: 771, baseHp: 10360, baseDef: 630, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/nahida.png' },
    { id: 'nilou', name: 'Nilou', element: 'Hydro', weapon: 'Sword', rarity: 5, baseAtk: 763, baseHp: 15185, baseDef: 640, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/nilou.png' },
    { id: 'cyno', name: 'Cyno', element: 'Electro', weapon: 'Polearm', rarity: 5, baseAtk: 787, baseHp: 13092, baseDef: 753, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/cyno.png' },
    { id: 'candace', name: 'Candace', element: 'Hydro', weapon: 'Polearm', rarity: 4, baseAtk: 730, baseHp: 11636, baseDef: 685, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/candace.png' },
    { id: 'layla', name: 'Layla', element: 'Cryo', weapon: 'Sword', rarity: 4, baseAtk: 731, baseHp: 11092, baseDef: 641, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/layla.png' },
    { id: 'faruzan', name: 'Faruzan', element: 'Anemo', weapon: 'Bow', rarity: 4, baseAtk: 740, baseHp: 9570, baseDef: 628, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/faruzan.png' },
    { id: 'wanderer', name: 'Wanderer (Scaramouche)', element: 'Anemo', weapon: 'Catalyst', rarity: 5, baseAtk: 803, baseHp: 10164, baseDef: 607, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/wanderer.png' },
    { id: 'yaoyao', name: 'Yaoyao', element: 'Dendro', weapon: 'Polearm', rarity: 4, baseAtk: 726, baseHp: 10736, baseDef: 660, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/yaoyao.png' },
    { id: 'alhaitham', name: 'Alhaitham', element: 'Dendro', weapon: 'Sword', rarity: 5, baseAtk: 782, baseHp: 13348, baseDef: 782, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/alhaitham.png' },
    { id: 'dehya', name: 'Dehya', element: 'Pyro', weapon: 'Claymore', rarity: 5, baseAtk: 765, baseHp: 14876, baseDef: 738, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/dehya.png' },
    { id: 'mika', name: 'Mika', element: 'Cryo', weapon: 'Polearm', rarity: 4, baseAtk: 728, baseHp: 10222, baseDef: 690, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/mika.png' },
    { id: 'baizhu', name: 'Baizhu', element: 'Dendro', weapon: 'Catalyst', rarity: 5, baseAtk: 769, baseHp: 13348, baseDef: 685, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/baizhu.png' },
    { id: 'kaveh', name: 'Kaveh', element: 'Dendro', weapon: 'Claymore', rarity: 4, baseAtk: 738, baseHp: 11101, baseDef: 632, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/kaveh.png' },
    { id: 'kirara', name: 'Kirara', element: 'Dendro', weapon: 'Sword', rarity: 4, baseAtk: 729, baseHp: 11813, baseDef: 630, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/kirara.png' },
    { id: 'lyney', name: 'Lyney', element: 'Pyro', weapon: 'Bow', rarity: 5, baseAtk: 787, baseHp: 12106, baseDef: 620, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/lyney.png' },
    { id: 'lynette', name: 'Lynette', element: 'Anemo', weapon: 'Sword', rarity: 4, baseAtk: 732, baseHp: 11170, baseDef: 665, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/lynette.png' },
    { id: 'freminet', name: 'Freminet', element: 'Cryo', weapon: 'Claymore', rarity: 4, baseAtk: 740, baseHp: 11048, baseDef: 686, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/freminet.png' },
    { id: 'neuvillette', name: 'Neuvillette', element: 'Hydro', weapon: 'Catalyst', rarity: 5, baseAtk: 768, baseHp: 14695, baseDef: 695, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/neuvillette.png' },
    { id: 'wriothesley', name: 'Wriothesley', element: 'Cryo', weapon: 'Catalyst', rarity: 5, baseAtk: 785, baseHp: 13593, baseDef: 568, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/wriothesley.png' },
    { id: 'furina', name: 'Furina', element: 'Hydro', weapon: 'Sword', rarity: 5, baseAtk: 762, baseHp: 15307, baseDef: 696, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/furina.png' },
    { id: 'charlotte', name: 'Charlotte', element: 'Cryo', weapon: 'Catalyst', rarity: 4, baseAtk: 734, baseHp: 9797, baseDef: 686, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/charlotte.png' },
    { id: 'navia', name: 'Navia', element: 'Geo', weapon: 'Claymore', rarity: 5, baseAtk: 796, baseHp: 12449, baseDef: 733, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/navia.png' },
    { id: 'chevreuse', name: 'Chevreuse', element: 'Pyro', weapon: 'Polearm', rarity: 4, baseAtk: 725, baseHp: 11856, baseDef: 648, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/chevreuse.png' },
    { id: 'gaming', name: 'Gaming', element: 'Pyro', weapon: 'Claymore', rarity: 4, baseAtk: 741, baseHp: 11267, baseDef: 632, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/gaming.png' },
    { id: 'xianyun', name: 'Xianyun', element: 'Anemo', weapon: 'Catalyst', rarity: 5, baseAtk: 801, baseHp: 12283, baseDef: 632, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/xianyun.png' },
    { id: 'chiori', name: 'Chiori', element: 'Geo', weapon: 'Sword', rarity: 5, baseAtk: 789, baseHp: 12142, baseDef: 843, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/chiori.png' },
    { id: 'arliecino', name: 'Arlecchino', element: 'Pyro', weapon: 'Polearm', rarity: 5, baseAtk: 806, baseHp: 13103, baseDef: 765, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/arliecino.png' },
    { id: 'sethos', name: 'Sethos', element: 'Electro', weapon: 'Bow', rarity: 4, baseAtk: 743, baseHp: 9461, baseDef: 601, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/sethos.png' },
    { id: 'clorinde', name: 'Clorinde', element: 'Electro', weapon: 'Sword', rarity: 5, baseAtk: 793, baseHp: 12256, baseDef: 771, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/clorinde.png' },
    { id: 'sigewinne', name: 'Sigewinne', element: 'Hydro', weapon: 'Bow', rarity: 5, baseAtk: 766, baseHp: 13500, baseDef: 618, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/sigewinne.png' },
    { id: 'emilie', name: 'Emilie', element: 'Dendro', weapon: 'Polearm', rarity: 5, baseAtk: 784, baseHp: 12518, baseDef: 750, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/emilie.png' },
    { id: 'kinich', name: 'Kinich', element: 'Dendro', weapon: 'Claymore', rarity: 5, baseAtk: 795, baseHp: 12016, baseDef: 731, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/kinich.png' },
    { id: 'mualani', name: 'Mualani', element: 'Hydro', weapon: 'Catalyst', rarity: 5, baseAtk: 770, baseHp: 12849, baseDef: 628, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/mualani.png' },
    { id: 'kachina', name: 'Kachina', element: 'Geo', weapon: 'Polearm', rarity: 4, baseAtk: 726, baseHp: 10736, baseDef: 691, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/kachina.png' },
    { id: 'ororon', name: 'Ororon', element: 'Electro', weapon: 'Bow', rarity: 4, baseAtk: 742, baseHp: 9500, baseDef: 605, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/ororon.png' },
    { id: 'chaska', name: 'Chasca', element: 'Anemo', weapon: 'Bow', rarity: 5, baseAtk: 788, baseHp: 12200, baseDef: 640, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/chaska.png' },
    { id: 'citlali', name: 'Citlali', element: 'Cryo', weapon: 'Catalyst', rarity: 5, baseAtk: 772, baseHp: 12630, baseDef: 670, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/citlali.png' },
    { id: 'mavuika', name: 'Mavuika', element: 'Pyro', weapon: 'Claymore', rarity: 5, baseAtk: 807, baseHp: 13100, baseDef: 748, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/mavuika.png' },
    { id: 'lan_yan', name: 'Lan Yan', element: 'Anemo', weapon: 'Catalyst', rarity: 4, baseAtk: 731, baseHp: 9600, baseDef: 610, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/lan_yan.png' },
    { id: 'yelan', name: 'Yelan', element: 'Hydro', weapon: 'Bow', rarity: 5, baseAtk: 792, baseHp: 14450, baseDef: 566, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/yelan.png' },
    { id: 'aino', name: "Aino", element: 'Hydro', weapon: 'Claymore', rarity: 4, baseAtk: 242, baseHp: 11201, baseDef: 607, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/aino.png' },
    { id: 'aloy', name: "Aloy", element: 'Cryo', weapon: 'Bow', rarity: 5, baseAtk: 234, baseHp: 10899, baseDef: 676, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/aloy.png' },
    { id: 'collei', name: "Collei", element: 'Dendro', weapon: 'Bow', rarity: 4, baseAtk: 200, baseHp: 9787, baseDef: 601, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/collei.png' },
    { id: 'columbina', name: "Columbina", element: 'Hydro', weapon: 'Catalyst', rarity: 5, baseAtk: 96, baseHp: 14695, baseDef: 515, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/columbina.png' },
    { id: 'dahlia', name: "Dahlia", element: 'Hydro', weapon: 'Sword', rarity: 4, baseAtk: 189, baseHp: 12506, baseDef: 560, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/dahlia.png' },
    { id: 'diona', name: "Diona", element: 'Cryo', weapon: 'Bow', rarity: 4, baseAtk: 212, baseHp: 9570, baseDef: 601, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/diona.png' },
    { id: 'dori', name: "Dori", element: 'Electro', weapon: 'Claymore', rarity: 4, baseAtk: 223, baseHp: 12397, baseDef: 723, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/dori.png' },
    { id: 'durin', name: "Durin", element: 'Pyro', weapon: 'Sword', rarity: 5, baseAtk: 347, baseHp: 12430, baseDef: 822, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/durin.png' },
    { id: 'escoffier', name: "Escoffier", element: 'Cryo', weapon: 'Polearm', rarity: 5, baseAtk: 347, baseHp: 13348, baseDef: 732, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/escoffier.png' },
    { id: 'flins', name: "Flins", element: 'Electro', weapon: 'Polearm', rarity: 5, baseAtk: 352, baseHp: 12491, baseDef: 809, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/flins.png' },
    { id: 'iansan', name: "Iansan", element: 'Electro', weapon: 'Polearm', rarity: 4, baseAtk: 257, baseHp: 10657, baseDef: 638, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/iansan.png' },
    { id: 'ifa', name: "Ifa", element: 'Anemo', weapon: 'Catalyst', rarity: 4, baseAtk: 178, baseHp: 10081, baseDef: 605, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/ifa.png' },
    { id: 'illuga', name: "Illuga", element: 'Geo', weapon: 'Polearm', rarity: 4, baseAtk: 191, baseHp: 11962, baseDef: 814, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/illuga.png' },
    { id: 'ineffa', name: "Ineffa", element: 'Electro', weapon: 'Polearm', rarity: 5, baseAtk: 330, baseHp: 12613, baseDef: 828, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/ineffa.png' },
    { id: 'jahoda', name: "Jahoda", element: 'Anemo', weapon: 'Bow', rarity: 4, baseAtk: 223, baseHp: 9646, baseDef: 580, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/jahoda.png' },
    { id: 'kuki_shinobu', name: "Kuki Shinobu", element: 'Electro', weapon: 'Sword', rarity: 4, baseAtk: 212, baseHp: 12289, baseDef: 751, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/kuki_shinobu.png' },
    { id: 'lauma', name: "Lauma", element: 'Dendro', weapon: 'Catalyst', rarity: 5, baseAtk: 255, baseHp: 10654, baseDef: 669, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/lauma.png' },
    { id: 'linnea', name: "Linnea", element: 'Geo', weapon: 'Bow', rarity: 5, baseAtk: 144, baseHp: 9895, baseDef: 907, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/linnea.png' },
    { id: 'lohen', name: "Lohen", element: 'Cryo', weapon: 'Polearm', rarity: 5, baseAtk: 344, baseHp: 12858, baseDef: 784, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/lohen.png' },
    { id: 'nefer', name: "Nefer", element: 'Dendro', weapon: 'Catalyst', rarity: 5, baseAtk: 344, baseHp: 12704, baseDef: 799, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/nefer.png' },
    { id: 'nicole', name: "Nicole", element: 'Pyro', weapon: 'Catalyst', rarity: 5, baseAtk: 342, baseHp: 10409, baseDef: 563, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/nicole.png' },
    { id: 'prune', name: "Prune", element: 'Anemo', weapon: 'Catalyst', rarity: 4, baseAtk: 221, baseHp: 9679, baseDef: 580, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/prune.png' },
    { id: 'sandrone', name: "Sandrone", element: 'Cryo', weapon: 'Claymore', rarity: 5, baseAtk: 342, baseHp: 13226, baseDef: 752, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/sandrone.png' },
    { id: 'shikanoin_heizou', name: "Shikanoin Heizou", element: 'Anemo', weapon: 'Catalyst', rarity: 4, baseAtk: 225, baseHp: 10657, baseDef: 684, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/shikanoin_heizou.png' },
    { id: 'skirk', name: "Skirk", element: 'Cryo', weapon: 'Sword', rarity: 5, baseAtk: 359, baseHp: 12417, baseDef: 806, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/skirk.png' },
    { id: 'tighnari', name: "Tighnari", element: 'Dendro', weapon: 'Bow', rarity: 5, baseAtk: 268, baseHp: 10850, baseDef: 630, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/tighnari.png' },
    { id: 'varesa', name: "Varesa", element: 'Electro', weapon: 'Catalyst', rarity: 5, baseAtk: 356, baseHp: 12699, baseDef: 782, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/varesa.png' },
    { id: 'varka', name: "Varka", element: 'Anemo', weapon: 'Claymore', rarity: 5, baseAtk: 353, baseHp: 12613, baseDef: 795, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/varka.png' },
    { id: 'xilonen', name: "Xilonen", element: 'Geo', weapon: 'Sword', rarity: 5, baseAtk: 275, baseHp: 12405, baseDef: 930, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/xilonen.png' },
    { id: 'xinyan', name: "Xinyan", element: 'Pyro', weapon: 'Claymore', rarity: 4, baseAtk: 249, baseHp: 11201, baseDef: 799, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/xinyan.png' },
    { id: 'yanfei', name: "Yanfei", element: 'Pyro', weapon: 'Catalyst', rarity: 4, baseAtk: 240, baseHp: 9352, baseDef: 587, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/yanfei.png' },
    { id: 'yumemizuki_mizuki', name: "Yumemizuki Mizuki", element: 'Anemo', weapon: 'Catalyst', rarity: 5, baseAtk: 215, baseHp: 12736, baseDef: 757, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/yumemizuki_mizuki.png' },
    { id: 'zibai', name: "Zibai", element: 'Geo', weapon: 'Sword', rarity: 5, baseAtk: 225, baseHp: 12919, baseDef: 957, baseCritRate: 5, baseCritDmg: 50, baseEnergyRegen: 100, baseElementalMastery: 0, icon: 'icons/characters/zibai.png' },
];

export function getCharacter(id: string): GICharacter | undefined {
    return CHARACTERS.find((c) => c.id === id);
}
