/**
 * @fileoverview Hand-curated WW resonator Inherent Skill self-buffs
 * @module adapters/game-definitions/wuthering-waves/character-passives.generated
 *
 * SELF stat buffs from a resonator's own Inherent Skills (SkillType 4 in the
 * Dimbreath datamine) — the WW equivalent of GI's character passive-talent
 * selfBuffs. See scripts/curate-ww-character-passives.cjs for methodology,
 * rejection categories, and the SkillType-4-is-not-Forte correction note.
 * DO NOT edit by hand — re-run scripts/curate-ww-character-passives.cjs.
 * 43 resonators, 57 buff entries (+ 3 hand-added entries, 2026-07-16/17
 * accuracy sweeps: Zhezhi's missed Forte-Circuit self-buff, Sigrika — a
 * wholly-new resonator this generator predates, and Augusta — same gap —
 * see inline comments).
 */

import type { BuffEntry } from '@shared/types/game-bundle';

export const CHARACTER_SELF_BUFFS: Record<string, Array<{ stat: string; label: string; value: number; conditional?: boolean; appliesTo?: string[]; scaleOff?: BuffEntry['scaleOff'] }>> = {
    // ADDED 2026-07-16 — Inherent Skill "Sky Over Water" had no entry at
    // all: "When Resonance Skill - Awakening Spring or Intro Skill -
    // Tinkling Jade hits the target, this attack's Crit Rate +80% and
    // Glacio DMG +240%, once every 25s" (wuthering.gg). Scoped to
    // 'skill'/'intro' — both are Suisui's only moves of each type.
    "suisui": [{"stat":"critRate","label":"Crit Rate +80%, on Awakening Spring/Tinkling Jade hit (Inherent I)","value":80,"conditional":true,"appliesTo":["skill","intro"]},{"stat":"elemDmg","label":"Glacio DMG +240%, on Awakening Spring/Tinkling Jade hit (Inherent I)","value":240,"conditional":true,"appliesTo":["skill","intro"]},{"stat":"atkPct","label":"When a Resonator other than Suisui takes a fatal blow, they will not be knocked out but will instead regain 50% of Suisui's current HP, while Suisui herself loses the same amount of HP. Suisui's HP will not go below 1 from this effect. This effect can be triggered once every 10 minutes. (Inherent II)","value":0,"conditional":false}],
    "rover-spectro": [{"stat":"dmgBonus","label":"Basic Atk (Resonating Echoes) DMG +60% (Inherent I)","value":60,"conditional":false,"appliesTo":["basic"]},{"stat":"atkPct","label":"ATK +15%, 5s after Heavy Attack Resonance (Inherent II)","value":15,"conditional":true}],
    "jinhsi": [{"stat":"elemDmg","label":"Spectro DMG Bonus +20% (Inherent I)","value":20,"conditional":false},{"stat":"atkPct","label":"DMG Multiplier of Intro Skill Loong's Halo is increased by 50%. (Inherent II)","value":0,"conditional":false}],
    "yinlin": [{"stat":"critRate","label":"Crit Rate +15%, 5s after Resonance Skill (Inherent I)","value":15,"conditional":true},{"stat":"dmgBonus","label":"Resonance Skill DMG +10% vs Sinner's-Mark targets (Inherent II)","value":10,"conditional":true,"appliesTo":["skill"]},{"stat":"atkPct","label":"ATK +10%, 4s, on Sinner's-Mark trigger (Inherent II)","value":10,"conditional":true}],
    "changli": [{"stat":"elemDmg","label":"Fusion DMG Bonus +20%, 4 stacks of Enflamement (Inherent I)","value":20,"conditional":true},{"stat":"elemDmg","label":"Fusion DMG Bonus +20%, after Heavy Atk/Liberation cast (Inherent II)","value":20,"conditional":true}],
    "camellya": [{"stat":"elemDmg","label":"Havoc DMG Bonus +15% (Inherent I)","value":15,"conditional":false},{"stat":"dmgBonus","label":"Basic Atk DMG +15% (Inherent II)","value":15,"conditional":false,"appliesTo":["basic"]}],
    "jiyan": [{"stat":"atkPct","label":"ATK +10%, 15s after Intro Skill (Inherent I)","value":10,"conditional":true},{"stat":"critDmg","label":"Crit DMG +12%, 8s on hit (Inherent II)","value":12,"conditional":true}],
    "calcharo": [{"stat":"dmgBonus","label":"Liberation DMG +10%, 15s after Heavy Atk Mercy (Inherent I)","value":10,"conditional":true,"appliesTo":["ult"]},{"stat":"atkPct","label":"When Heavy Attack \"Death Messenger\" hits the target, the damage taken by Calcharo is reduced by 15% for 5s. (Inherent II)","value":0,"conditional":false}],
    "encore": [{"stat":"dmgBonus","label":"Liberation DMG +10% while HP>70%, during Cosmos Rave (Inherent I)","value":10,"conditional":true,"appliesTo":["ult"]},{"stat":"elemDmg","label":"Fusion DMG Bonus +10%, 10s after Resonance Skill cast (Inherent II)","value":10,"conditional":true}],
    "sanhua": [{"stat":"dmgBonus","label":"Res. Skill DMG +20%, 8s after Intro Skill (Inherent I)","value":20,"conditional":true,"appliesTo":["skill"]},{"stat":"dmgBonus","label":"Forte Circuit DMG +20%, 8s after Basic Atk 5 (Inherent II)","value":20,"conditional":true,"appliesTo":["forte"]}],
    "yangyang": [{"stat":"elemDmg","label":"Aero DMG Bonus +8%, 8s after Intro Skill (Inherent II)","value":8,"conditional":true},{"stat":"atkPct","label":"Yangyang recovers 30 STA after she casts a Mid-air Attack Feather Release. (Inherent I)","value":0,"conditional":false}],
    "chixia": [{"stat":"dmgBonus","label":"Resonance Skill DMG +50% (Inherent I)","value":50,"conditional":false,"appliesTo":["skill"]},{"stat":"atkPct","label":"ATK +30% (max 30 stacks), during Resonance Skill (Inherent II)","value":30,"conditional":true}],
    "danjin": [{"stat":"dmgBonus","label":"Res. Skill DMG +20%, via Dodge-Counter trigger (Inherent I)","value":20,"conditional":true,"appliesTo":["skill"]},{"stat":"dmgBonus","label":"Heavy Atk DMG +30%, 5s after Res. Skill (Inherent II)","value":30,"conditional":true,"appliesTo":["heavy"]}],
    "mortefi": [{"stat":"dmgBonus","label":"Res. Skill DMG +25%, 8s after casting (Inherent I)","value":25,"conditional":true,"appliesTo":["skill"]},{"stat":"dmgBonus","label":"Liberation DMG +75% (max 50 stacks), during Burning Rhapsody (Inherent II)","value":75,"conditional":true,"appliesTo":["ult"]}],
    "taoqi": [{"stat":"defPct","label":"DEF +15% while Rocksteady Shield active (Inherent I)","value":15,"conditional":true},{"stat":"atkPct","label":"After Heavy Attack Strategic Parry is successfully triggered, 25 STA is recovered. (Inherent II)","value":0,"conditional":false}],
    "xiangli-yao": [{"stat":"elemDmg","label":"Electro DMG Bonus +20% (max 4 stacks), 8s after Res. Skill (Inherent I)","value":20,"conditional":true},{"stat":"atkPct","label":"When in Intuition triggered by Resonance Liberation, Xiangli Yao's resistance to interruption is enhanced. (Inherent II)","value":0,"conditional":false}],
    "zhezhi": [{"stat":"atkPct","label":"ATK +18% (max 3 stacks), 27s after Res. Skill (Inherent I)","value":18,"conditional":true},{"stat":"dmgBonus","label":"Basic Atk DMG +18%, 27s after Creation's Zenith (Forte Circuit)","value":18,"conditional":true,"appliesTo":["basic"]},{"stat":"atkPct","label":"After Outro Skill is cast, restore 15 Resonance Energy for the incoming Resonator. (Inherent II)","value":0,"conditional":false}],
    "shorekeeper": [{"stat":"energyRegen","label":"Energy Regen +10%, near Stellarealm (Inherent II)","value":10,"conditional":true},{"stat":"atkPct","label":"When a Resonator other than Shorekeeper takes a fatal blow, they will not be knocked out and will instead be healed for 50% of Shorekeeper's HP while Shorekeeper loses the same amount of HP. Shorekeeper's HP will not go below 1 from this effect. This effect can be triggered once every 10 minutes. (Inherent I)","value":0,"conditional":false}],
    "roccia": [{"stat":"atkPct","label":"ATK +20%, 12s after Res. Skill/Heavy Atk (Inherent I)","value":20,"conditional":true},{"stat":"atkPct","label":"After casting Outro Skill, the Utility of the incoming Resonator is replaced with Magic Box. Magic Box- Upon use, pull nearby targets toward the Magic Box, dealing 100 points of Havoc DMG. This skill is considered Echo Skill that deals Utility DMG.- The Magic Box lasts for 14s or until the Resonator is switched out. (Inherent II)","value":0,"conditional":false}],
    "cantarella": [{"stat":"healingBonus","label":"Healing Bonus +20% (Inherent I)","value":20,"conditional":false},{"stat":"elemDmg","label":"Havoc DMG Bonus +12% (max 2 stacks), 10s after Echo Skill (Inherent II)","value":12,"conditional":true}],
    "yuanwu": [{"stat":"dmgBonus","label":"Res. Skill (Thunder Uprising) DMG +40% (Inherent I)","value":40,"conditional":false,"appliesTo":["skill"]},{"stat":"atkPct","label":"The ranges of the Resonance Skills Thunder Field and Thunder Uprising are greatly expanded. When switched off the field during combat, if \"Readiness\" is not full, Yuanwu will automatically leave 1 Resonance Skill Thunder Wedge in place. (Inherent II)","value":0,"conditional":false}],
    "lumi": [{"stat":"elemDmg","label":"Electro DMG Bonus +10%, in Red Light Mode (Inherent I)","value":10,"conditional":true},{"stat":"atkPct","label":"ATK +10%, 5s after Energized Pounce/Rebound (Inherent II)","value":10,"conditional":true}],
    // Confirmed 2026-07-16 (was missing entirely). "Diligent Practice"
    // (next Mountain Roamer +150% DMG) not added — a named-move-specific
    // bonus with no clean appliesTo category (Furious Punches shares
    // Mountain Roamer's 'skill' scope and would be wrongly buffed too).
    "lingyang": [{"stat":"dmgBonus","label":"Intro Skill DMG +50% (Inherent I, \"Lion's Pride\")","value":50,"conditional":false,"appliesTo":["intro"]},{"stat":"atkPct","label":"Under the Forte Circuit Striding Lion state, within 3s after each Basic Attack, the next Forte Circuit Mountain Roamer will deal an additional Glacio DMG, equal to 150% of Mountain Roamer DMG, considered as Resonance Skill DMG. (Inherent II)","value":0,"conditional":false}],
    "youhu": [{"stat":"elemDmg","label":"Glacio DMG Bonus +15%, 14s after Intro Skill (Inherent II)","value":15,"conditional":true},{"stat":"atkPct","label":"Restore HP for all nearby party members based on 30% of the healing provided by Resonance Skill Scroll Divination when Resonance Skill Antique Appraisal is cast. (Inherent I)","value":0,"conditional":false}],
    "brant": [{"stat":"elemDmg","label":"Fusion DMG Bonus +15%, during Mid-air Attacks (Inherent II)","value":15,"conditional":true},{"stat":"atkPct","label":"Healing provided by Waves of Acclaims is increased by 20%. (Inherent I)","value":0,"conditional":false}],
    "phoebe": [{"stat":"elemDmg","label":"Spectro DMG Bonus +12%, in Absolution+Confession status (Inherent II)","value":12,"conditional":true},{"stat":"atkPct","label":"Mid-air Heavy Attack can be cast 1 more times. (Inherent I)","value":0,"conditional":false}],
    "ciaccona": [{"stat":"dmgBonus","label":"Heavy Atk (Quadruple Downbeat) DMG +30% (Inherent II)","value":30,"conditional":true,"appliesTo":["heavy"]},{"stat":"atkPct","label":"Casting Resonance Liberation Singer's Triple Cadenza grants Ciaccona a Shield equal to 100% of her Max HP for 4s. Switching out Ciaccona removes the Shield. (Inherent I)","value":0,"conditional":false}],
    "zani": [{"stat":"elemDmg","label":"Spectro DMG Bonus +12%, 14s after Intro Skill (Inherent I)","value":12,"conditional":true},{"stat":"atkPct","label":"When in Ready Stance, all DMG taken is reduced by 40%. (Inherent II)","value":0,"conditional":false}],
    "phrolova": [{"stat":"critDmg","label":"Crit DMG +25% (10 Aftersound stacks on combat entry) (Inherent II)","value":25,"conditional":false},{"stat":"atkPct","label":"Casting Echo Skill grants increased resistance to interruption and reduces damage taken by 30% for 15s.After casting Suite of Quietus, Suite of Immortality, and Echo Skill, the next Volatile Note becomes Volatile Note - Cadenza. (Inherent I)","value":0,"conditional":false}],
    // FIXED 2026-07-17 — real Inherent II ("Wind's Indelible Imprint") is
    // graduated: 1-3 stacks grants +30% flat, 4-6 stacks scales +10%/stack
    // up to +60% at 6. Base-kit max Aero Erosion stack is only 3 (6 needs
    // Sequence 2 or an Aero Rover teammate), so 60% was unreachable/wrong at
    // base kit — corrected to the realistically-modelable +30% (wuthering.wiki).
    "cartethyia": [{"stat":"elemDmg","label":"DMG Amplified +30% vs Aero-Erosion targets, +10%/stack past 3 up to +60% at 6 (Inherent II)","value":30,"conditional":true},{"stat":"atkPct","label":"The healing received by all Resonators other than Cartethyia/Fleurdelys in the team is increased by 20% and their resistance to interruption is enhanced. If Rover: Aero is in the team, Rover: Aero additionally restores 25 Windstrings upon casting Omega Storm. (Inherent I)","value":0,"conditional":false}],
    // ADDED 2026-07-17 — Forte resource "Crown of Wills" base-kit effect had
    // no entry at all: "Each stack grants 15% Electro DMG Bonus" (max 1
    // stack at base) — wuthering.gg.
    "augusta": [{"stat":"elemDmg","label":"Electro DMG Bonus +15%, 1 stack of Crown of Wills","value":15,"conditional":true},{"stat":"atkPct","label":"When Augusta deals damage, she gains a shield equal to 350 + 2.5% of her Max HP for 5s, triggered once every 0.5s. This effect is unstackable. This Shield will not be passed on to the incoming Resonator. (Inherent I)","value":0,"conditional":false},{"stat":"atkPct","label":"When Augusta is out of combat for over 4s, she gains the following effects that can be triggered once every 4s:- If Majesty is less than 1 stack, restore 1 stack.- Fully restore Crown of Wills. (Inherent II)","value":0,"conditional":false}],
    "buling": [{"stat":"healingBonus","label":"Healing Bonus +25% vs targets <50% HP (Inherent I)","value":25,"conditional":true},{"stat":"atkPct","label":"Targets damaged by Intro Skill - Summon and Smite obtain 4 stacks of Electro Flare. This effect is triggered once every 10s. (Inherent II)","value":0,"conditional":false}],
    "galbrena": [{"stat":"elemDmg","label":"DMG Amplified +20% (max 4 stacks) (Inherent I)","value":20,"conditional":true},{"stat":"atkPct","label":"Casting Basic Attack Stage 4, Basic Attack - Seraphic Execution Stage 5, Heavy Attack - Volley of Death Stage 3, and Heavy Attack - Flamewing Verdict Stage 3 recovers 10 points of STA. (Inherent II)","value":0,"conditional":false}],
    "chisa": [{"stat":"elemDmg","label":"Havoc DMG Bonus +20%, 12s after Intro Skill/Liberation (Inherent II)","value":20,"conditional":true},{"stat":"healingBonus","label":"Healing Bonus +20%, 12s after Intro Skill/Liberation (Inherent II)","value":20,"conditional":true},{"stat":"atkPct","label":"When a Resonator in the team defeats a target marked by Unseen Snare, the Cooldown of Chisa's Resonance Skill Eye of Unraveling is reset, triggered up to once every 3s. (Inherent I)","value":0,"conditional":false}],
    // ADDED 2026-07-17 — a wholly-new resonator this generator predates
    // (v3.5 Phase 1). Inherent I "Unbroken Vow": each Havoc Bane stack on the
    // target Amplifies DMG by 10% (stacks 1-3) then 12% (stacks 4-6), max
    // +66% at 6 stacks — api.encore.moe/en/character/1610. Modeled as a flat
    // assume-max-stacks toggle, same convention as Cartethyia's similar
    // stacked-DMG-Amp Inherent above.
    "yangyang-xuanling": [{"stat":"elemDmg","label":"DMG Amplified +66% at 6 Havoc Bane stacks on target (Inherent I)","value":66,"conditional":true}],
    "qiuyuan": [{"stat":"dmgBonus","label":"Heavy Atk DMG +50%, after entering Inksplash of Mind (Inherent I)","value":50,"conditional":true,"appliesTo":["heavy"]},{"stat":"atkPct","label":"ATK +10%, 20s on Flowing Panacea consume (Inherent II)","value":10,"conditional":true}],
    "lynae": [{"stat":"elemDmg","label":"Spectro DMG Bonus +25%, 9s after Intro Skill (Inherent II)","value":25,"conditional":true},{"stat":"atkPct","label":"After casting Basic Attack - Visual Impact, Lynae leaves Spray Paint on the ground and continuously inflicts Photochromic Flux on targets within the Spray Paint for 5s, triggered once every 2s. When Spray Paint is on the ground, switching to another Resonance Mode doesn't affect the Photochromic Flux effects inflicted by the Spray Paint.With Lynae in the team, the expedition motorbike's Energy Tank expands by 600 points. Lynae enters Kaleidoscopic Parade automatically while on the expedition motorbike and restores 20% of Lumiflow per second. (Inherent I)","value":0,"conditional":false}],
    // Base-kit self-scaling on her own Resonance Liberation "Critical
    // Protocol" (confirmed 2026-07-16, wuthering.gg, distinct from the
    // Sequence 2 TEAM buff above — this one only affects Mornye's own
    // ultimate): "For every 1% of Energy Regen exceeding 100%, this skill
    // gains 0.5% Crit Rate (up to 80%) and 1% Crit DMG (up to 160%)."
    "mornye": [{"stat":"energyRegen","label":"Energy Regen +10% (Inherent I)","value":10,"conditional":false},{"stat":"critRate","label":"Crit Rate (Resonance Liberation, ER-scaled)","value":0.5,"conditional":true,"appliesTo":["ult"],"scaleOff":{"sourceStat":"energyRegen","basis":"total","ratio":0.5,"offset":100,"cap":80}},{"stat":"critDmg","label":"Crit DMG (Resonance Liberation, ER-scaled)","value":1,"conditional":true,"appliesTo":["ult"],"scaleOff":{"sourceStat":"energyRegen","basis":"total","ratio":1,"offset":100,"cap":160}},{"stat":"atkPct","label":"Casting Resonance Skill - Expectation Error or Resonance Skill - Distributed Array grants Proof of Boundedness to all Resonators in the team:- Proof of Boundedness lasts for 60s and can be gained once every 5 min.- When the active Resonator takes DMG greater than 30% of their Max HP, they instead take DMG equal to 30% of their Max HP. This effect can trigger up to 3 times. Proof of Boundedness is removed after triggering it 3 times.- When the active Resonator takes a fatal blow, they are not downed by this instance of damage. This effect can trigger up to 1 times. Proof of Boundedness is removed after triggering it 1 times.- When Proof of Boundedness is removed, the active Resonator restores HP equal to 150% of Mornye's DEF. (Inherent II)","value":0,"conditional":false}],
    "luuk-herssen": [{"stat":"atkPct","label":"ATK +25%, 20s after ally Tune Strain-Shifting/Tune Break (Inherent II)","value":25,"conditional":true},{"stat":"atkPct","label":"When Resonators in the team directly damage and defeat targets, if the targets are affected by Tune Strain - Interfered:- If Luuk Herssen has no Perpetuating Daytime, gain stacks of Perpetuating Daytime equal to the stacks of Tune Strain - Interfered.- If Luuk Herssen already has Perpetuating Daytime, and the target's stacks of Tune Strain - Interfered exceed the current stacks of Perpetuating Daytime, increase Perpetuating Daytime's stacks to match the target's Tune Strain - Interfered stacks.Perpetuating Daytime- When Resonators in the team casts Tune Break, if the target is affected by Tune Strain - Shifting, Luuk Herssen loses all stacks of Perpetuating Daytime, then apply equal stacks of Tune Strain - Interfered on the target, up to the target's current Tune Strain - Interfered stack cap. Cooldown: 1s.Luuk Herssen loses all stacks of Perpetuating Daytime and will not be able to obtain any new stacks when knocked out.- Perpetuating Daytime stacks up to 2 times. (Inherent I)","value":0,"conditional":false}],
    "aemeath": [{"stat":"dmgBonus","label":"Heavy Atk DMG Amplification +200%, in Instant Response state (Inherent I)","value":200,"conditional":true,"appliesTo":["heavy"]},{"stat":"atkPct","label":"In Resonance Mode - Tune Rupture, when Resonators in the team inflict Tune Rupture - Shifting or deal Tune Rupture DMG, Aemeath's Crit. DMG increases by 20%, up to 3 times. Each Resonator can only trigger this effect once.With 3 stacks, Resonance Liberation Heavenfall Edict: Finale DMG is Amplified by 25%.Resonators joining the team or switching Resonance Mode resets this effect.In Resonance Mode - Fusion Burst, when Resonators in the team inflict Fusion Burst, Aemeath's Crit. DMG increases by 30%, up to 2 times. Each Resonator can only trigger this effect once.With 2 stacks, Resonance Liberation Heavenfall Edict: Finale DMG is Amplified by 25%.Resonators joining the team or switching Resonance Mode resets this effect. (Inherent II)","value":0,"conditional":false}],
    "hiyuki": [{"stat":"critDmg","label":"Crit DMG +40%, at 1+ stacks of Snow Rust (Inherent I)","value":40,"conditional":true},{"stat":"atkPct","label":"Once Hiyuki leaves the combat state or recovers after being knocked out, when she stays out of combat for 4s with fewer than 1 point of Snowforged Blade, restore 1 point. (Inherent II)","value":0,"conditional":false}],
    "jianxin": [{"stat":"dmgBonus","label":"Liberation DMG +20% (Inherent I)","value":20,"conditional":false,"appliesTo":["ult"]},{"stat":"atkPct","label":"The Shield obtained from Heavy Attack Primordial Chi Spiral is increased by 20%. (Inherent II)","value":0,"conditional":false}],
    "lucy": [{"stat":"elemDmg","label":"All DMG Amplification +15% (max 2 stacks), via Network Backdoor (Inherent II)","value":15,"conditional":true},{"stat":"elemDmg","label":"Hack DMG Multiplier +15% (max 2 stacks), via Network Backdoor (Inherent II)","value":15,"conditional":true},{"stat":"atkPct","label":"When Lucy is the active Resonator in the team, if she takes no damage for 8s, she gains 1 stacks of Optical Illusion. Max 1 stacks by default.Optical Illusion: When attacked, reduce this instance of DMG by 100%. If Lucy is hit or launched from the attack, she immediately recovers and triggers a successful Dodge if she's on the ground. After this effect is triggered, remove 1 stacks of Optical Illusion. This effect can be triggered up to 1 times every 0.5s. (Inherent I)","value":0,"conditional":false}],
    "rebecca": [{"stat":"atkPct","label":"ATK +20% (max 2 stacks), 12s after trigger (Inherent I)","value":20,"conditional":true},{"stat":"atkPct","label":"Heavy Attack - Rat-tat-tat!: Huntress and Heavy Attack - Bang-bang-bang!: Guts gain increased resistance to interruption.When Rebecca casts Resonance Liberation - Party 'til Dawn!, the ATK of all nearby Resonators in the team is increased by 20% for 30s. (Inherent II)","value":0,"conditional":false}],
    "rover-aero": [{"stat":"atkPct","label":"ATK +20%, 10s after Intro Skill (Inherent I)","value":20,"conditional":true},{"stat":"atkPct","label":"Increase Healing from Resonance Liberation Omega Storm by 20%. (Inherent II)","value":0,"conditional":false}],
    "rover-havoc": [{"stat":"elemDmg","label":"Havoc DMG Bonus +20%, in Dark Surge state (Inherent I)","value":20,"conditional":true},{"stat":"atkPct","label":"While in the Dark Surge state, Basic Attack recovers 1 extra Resonance Energy when it hits a target. This effect can be triggered 1 time per second. (Inherent II)","value":0,"conditional":false}],
    "rover-electro": [{"stat":"dmgBonus","label":"Res. Skill DMG +20%, 20s after held-cast Overshock (Inherent II)","value":20,"conditional":true,"appliesTo":["skill"]},{"stat":"atkPct","label":"Resonance Skill Overshock inflicts 10 stacks of Electro Flare on the target it damages. (Inherent I)","value":0,"conditional":false}],
    // ADDED 2026-07-16 — at max (6) stacks of Blessing of Runes, Sigrika
    // grants HERSELF an extra 30% Aero DMG Bonus AND 30% Echo Skill DMG
    // Bonus, on top of the team-wide per-stack tier already modeled in
    // bundle.ts's cb-ww-sigrika/cb-ww-sigrika-echo. The Echo-Skill-DMG half
    // uses the 'echo' appliesTo scope added 2026-07-16 (see optimizer.ts's
    // canonScope()) — correctly inert until Echo Skill's own damage is
    // modeled (depends on the equipped Echo, out of scope for this pass).
    // 3rd clause of "True Names Aligned" added 2026-07-16 (was missing
    // entirely): "For every 1% of Energy Regen over 125%, Sigrika gains 2%
    // Echo Skill DMG Bonus, up to 50%" (wuthering.gg).
    "sigrika": [{"stat":"elemDmg","label":"Aero DMG Bonus +30%, at 6 stacks of Blessing of Runes (Inherent I)","value":30,"conditional":true},{"stat":"dmgBonus","label":"Echo Skill DMG Bonus +30%, at 6 stacks of Blessing of Runes (Inherent I)","value":30,"conditional":true,"appliesTo":["echo"]},{"stat":"dmgBonus","label":"Echo Skill DMG Bonus (ER-scaled, over 125%)","value":2,"conditional":true,"appliesTo":["echo"],"scaleOff":{"sourceStat":"energyRegen","basis":"total","ratio":2,"offset":125,"cap":50}},{"stat":"atkPct","label":"When any nearby Resonators in the team cast Echo Skill, Sigrika gains a stack of Blessing of Runes, up to 6 stacks. Echoes with the same name can only trigger this effect once. This effect resets upon a lineup change.Blessing of RunesEach stack of Blessing of Runes grants the active Resonator in the team 3% Aero DMG Bonus and 3% Echo Skill DMG Bonus.When Blessing of Runes reaches 6 stacks, Sigrika additionally gains 30% Aero DMG Bonus and Echo Skill DMG Bonus.For every 1% of Sigrika's Energy Regen over 125%, Sigrika gains 2% Echo Skill DMG Bonus for up to 50%. (Inherent II)","value":0,"conditional":false}],
    "verina": [{"stat":"atkPct","label":"Verina protects a team member from fatal damage and grants a shield with strength equal to 120% of Verina's ATK, lasting for 10s. This can be triggered 1 time every 10 minutes. (Inherent I)","value":0,"conditional":false},{"stat":"atkPct","label":"When Verina casts Heavy Attack Starflower Blooms, Mid-air Attack Starflower Blooms, Resonance Liberation Arboreal Flourish or Outro Skill Blossom, all team members' ATK are increased by 20% for 20s. (Inherent II)","value":0,"conditional":false}],
    "baizhi": [{"stat":"atkPct","label":"When Baizhi casts Resonance Skill Emergency Plan, You'tan generates a field of Euphonia that lasts for 15s. EuphoniaATK of the Resonators who pick up Euphonia is increased by 15% for 20s. (Inherent I)","value":0,"conditional":false},{"stat":"atkPct","label":"Baizhi's Heavy Attack on hit heals the character with the lowest HP on a nearby team by 0.25% of her Max HP. (Inherent II)","value":0,"conditional":false}],
    "aalto": [{"stat":"atkPct","label":"Aalto's Heavy Attack will always critically hit, triggered once every 30s. (Inherent I)","value":0,"conditional":false},{"stat":"atkPct","label":"Aalto will continuously recover STA when he is in the Forte Circuit Mistcloak Dash state. (Inherent II)","value":0,"conditional":false}],
    "carlotta": [{"stat":"atkPct","label":"After casting Resonance Skill Chromatic Splendor, Carlotta can perform Mid-air Attacks while being immune to any DMG or interruptions before the Mid-air Attack deals DMG.When Carlotta is on the team, the active Resonator's Flight STA cost is reduced by 20%. (Inherent I)","value":0,"conditional":false},{"stat":"atkPct","label":"Intro Skill Wintertime Aria, Resonance Skill Chromatic Splendor, Resonance Liberation Death Knell, and Heavy Attack Imminent Oblivion can inflict Deconstruction. (Inherent II)","value":0,"conditional":false}],
    "lupa": [{"stat":"atkPct","label":"After dashing for 2.5s, Lupa enters Sprint state. The next Basic Attack is replaced with Basic Attack - Starfall.Gain increased resistance to interruptions while casting Heavy Attack - Wolf's Gnawing, Heavy Attack - Wolf's Claw, and Mid-air Attack - Firestrike. (Inherent I)","value":0,"conditional":false},{"stat":"atkPct","label":"Defeating a marked target resets the cooldown of Resonance Skill Shewolf's Hunt.Resonance Liberation - GloryCasting Resonance Liberation Fire-Kissed Glory grants Glory. Within 35s:Attacks of all Resonators in the team ignore 3% of the target's Fusion RES. For each Fusion Resonator in the team other than Lupa, this effect increases by 3%, up to the maximum of 9%. When there are 3 Fusion Resonators in the team, Resonators' attacks further ignore 6% Fusion RES. (Inherent II)","value":0,"conditional":false}],
    "iuno": [{"stat":"atkPct","label":"Every time Iuno casts Basic Attack, Heavy Attack, Dodge Counter, Resonance Skill, Resonance Liberation, or Intro Skill, she gains 1 Shield equal to 32% of her ATK for 15s. This Shield will not be passed on to the incoming Resonator. (Inherent I)","value":0,"conditional":false},{"stat":"atkPct","label":"When Iuno casts Intro Skill or Resonance Liberation, she immediately gains 5 stacks of Blessing of the Wan Light. (Inherent II)","value":0,"conditional":false}],
    "denia": [{"stat":"atkPct","label":"When Denia engages in combat in Stagecraft Form: restore Dark Cores to 2 if she has fewer than 2; restore Void Particle to 20 points if she has fewer than 20. This effect can be triggered once every 12s. (Inherent I)","value":0,"conditional":false},{"stat":"atkPct","label":"While in the Entropy Shift states, Denia obtains the following effects based on her current Resonance Mode:- Resonance Mode - Fusion Burst: All Resonators in the team gain 30% Fusion DMG Bonus.- Resonance Mode - Tune Strain: All Resonators in the team gain 10 Tune Break Boost. When a Resonator in the team has an Off-Tune Buildup Rate over 100%, every 10% that runs over increases the Resonator's Tune Break Boost by 8, up to 40. (Inherent II)","value":0,"conditional":false}],
    "lucilla": [{"stat":"atkPct","label":"When Focus Ring is deployed, Lucilla slows targets within her shot.While casting Resonance Skill - Spotlight, Lucilla grants the following enhancements based on her Resonance Mode:- When in Resonance Mode - Glacio Chafe, Glacio RES of targets within a certain range around the active Resonator is reduced by 8% for 30s. If an enemy falls to Glacio Chafe DMG during this time, it counts as caused by the nearest active Resonator.- When in Resonance Mode - Echo, Resonators in the team gain 25% Echo Skill DMG Bonus for 30s.These enhancements end when Lucilla switches the Resonance Mode. (Inherent I)","value":0,"conditional":false},{"stat":"atkPct","label":"Film Roll can now be stacked up to 10 stacks, and Zoom up to 4 stacks.Each time Lucilla consumes Photo when in Resonance Mode - Glacio Chafe/Resonance Mode - Echo, she gains 2 stacks of Film Roll/1 stacks of Zoom. (Inherent II)","value":0,"conditional":false}],
};

export default CHARACTER_SELF_BUFFS;
