/**
 * @fileoverview Wuthering Waves weapon database (FULL roster, auto-generated)
 * @module adapters/game-definitions/wuthering-waves/weapons
 *
 * Accurate lvl-90 base ATK + secondary from the Dimbreath datamine (WeaponConf x
 * WeaponPropertyGrowth, secondary type via PropertyIndex) + parsed passive self-buffs
 * (WeaponConf.Desc/DescParams). Regenerate:
 * WW_CACHE=<dir> node --max-old-space-size=3072 scripts/import-wuwa-weapon-passives.cjs. 120 weapons
 * (8 added 2026-07-12 from api.encore.moe — the Dimbreath datamine is stale for
 * anything past ~9 characters/weapons old, see [[ww-missing-content-2026-07-12]]).
 */
import type { WeaponType, StatType } from '@shared/types/game-definition';
export interface WUWeapon {
    id: string; name: string; weaponType: WeaponType; rarity: number;
    baseAtk: number; secondaryStat: StatType; secondaryValue: number;
    /** Passive description (human-readable, R1 values). */
    passive?: string;
    /** TEAM buffs the passive deploys to the party (support weapons only). */
    buffs?: Array<{ stat: string; label: string; value: number; appliesTo?: string[]; autoTrigger?: { skillIds: string[]; durationSeconds: number } }>;
    /** SELF buffs the passive grants the wielder (R1). Unconditional (conditional:false) auto-apply; conditional are opt-in toggles / trigger-conditional. `appliesTo` scopes a DMG% buff. */
    selfBuffs?: Array<{ stat: string; label: string; value: number; conditional?: boolean; appliesTo?: string[]; autoTrigger?: { skillIds: string[]; durationSeconds: number } }>;
    icon: string;
}
export const WEAPONS: WUWeapon[] = [
    { id: "abyss-surges", name: "Abyss Surges", weaponType: "Gauntlets", rarity: 5, baseAtk: 588, secondaryStat: "ATK%", secondaryValue: 36.5, passive: "Increases Energy Regen by 12.8%. When hitting a target with Resonance Skill, increases Basic Attack DMG Bonus by 10%, lasting for 8s. When hitting a target with Basic Attacks, increases Resonance Skill DMG Bonus by 10%, lasting for 8s.", selfBuffs: [{"stat":"energyRegen","label":"Energy Regen","value":12.8,"conditional":false},{"stat":"dmgBonus","label":"Basic DMG","value":10,"conditional":true,"appliesTo":["basic"],"autoTrigger":{"skillIds":["skill"],"durationSeconds":8}},{"stat":"dmgBonus","label":"Res. Skill DMG","value":10,"conditional":true,"appliesTo":["skill"],"autoTrigger":{"skillIds":["basic"],"durationSeconds":8}}], icon: "icons/weapons/abyss-surges.webp" },
    { id: "ages-of-harvest", name: "Ages of Harvest", weaponType: "Broadblade", rarity: 5, baseAtk: 588, secondaryStat: "CRIT Rate", secondaryValue: 24.3, passive: "Grants 12% Attribute DMG Bonus. Casting Intro Skill gives the equipper Ageless Marking, which grants 24% Resonance Skill DMG Bonus for 12s. Casting Resonance Skill gives the equipper Ethereal Endowment, which grants 24% Resonance Skill DMG Bonus for 12s.", selfBuffs: [{"stat":"elemDmg","label":"DMG Bonus","value":12,"conditional":false},{"stat":"dmgBonus","label":"Res. Skill DMG","value":24,"conditional":true,"appliesTo":["skill"],"autoTrigger":{"skillIds":["intro","skill"],"durationSeconds":12}}], icon: "icons/weapons/ages-of-harvest.webp" },
    { id: "blazing-brilliance", name: "Blazing Brilliance", weaponType: "Sword", rarity: 5, baseAtk: 588, secondaryStat: "CRIT DMG", secondaryValue: 48.6, passive: "ATK increased by 12%. The wielder gains 1 stack of Searing Feather upon dealing damage, which can be triggered once every 0.5s, and gains 5 stacks of the same effect upon casting Resonance Skill. Each stack of Searing Feather gives 4% additional Resonance Skill DMG Bonus for up to 14 stacks. After reaching the max stacks, all stacks will be removed in 12s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Res. Skill DMG · 14 stacks","value":56,"conditional":true,"appliesTo":["skill"]}], icon: "icons/weapons/blazing-brilliance.webp" },
    { id: "blazing-justice", name: "Blazing Justice", weaponType: "Gauntlets", rarity: 5, baseAtk: 588, secondaryStat: "CRIT DMG", secondaryValue: 48.6, passive: "Increases ATK by 12%. Casting Basic Attack grants the following effects: Dealing damage ignores 8% of the target's DEF and Amplifies Spectro Frazzle DMG dealt by 50% for 6s. Retriggering the effect resets its duration.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Spectro Frazzle DMG","value":50,"conditional":true,"appliesTo":["frazzle"],"autoTrigger":{"skillIds":["basic"],"durationSeconds":6}},{"stat":"defIgnore","label":"DEF Ignore","value":8,"conditional":true,"autoTrigger":{"skillIds":["basic"],"durationSeconds":6}}], icon: "icons/weapons/blazing-justice.webp" },
    // FIXED 2026-07-17 — the "Rover:Aero ult -> team Aero DMG amp" clause is
    // restricted to ONE element for a team-wide buff. Turns out no new schema
    // field was needed: `computeBuildStats` already routes a buff whose
    // `stat` matches the TARGET character's own elemKey (e.g. 'aeroDmg' for
    // an Aero character) into their elemDmg, and silently no-ops it for
    // every other element (`ek` comparison in `apply()`) — this was already
    // exercised for a character's own innate elemental stat, just never used
    // by a BUFF before. Previously left unmodeled based on a wrong assumption
    // that no such mechanism existed.
    { id: "bloodpacts-pledge", name: "Bloodpact's Pledge", weaponType: "Sword", rarity: 5, baseAtk: 588, secondaryStat: "Energy Regen", secondaryValue: 38.9, passive: "Providing Healing increases Resonance Skill DMG by 10% for 6s. When Rover: Aero casts Resonance Skill Unbound Flow, Aero DMG dealt by nearby Resonators on the field is Amplified by 10% for 30s.", selfBuffs: [{"stat":"dmgBonus","label":"Res. Skill DMG","value":10,"conditional":true,"appliesTo":["skill"]}], buffs: [{"stat":"aeroDmg","label":"Aero DMG (Aero characters only)","value":10}], icon: "icons/weapons/bloodpacts-pledge.webp" },
    { id: "boson-astrolabe", name: "Boson Astrolabe", weaponType: "Rectifier", rarity: 5, baseAtk: 525, secondaryStat: "Energy Regen", secondaryValue: 38.9, passive: "Increases ATK by 12%. After a Resonator in the team casts a Tune Break skill, it grants a 12% ATK increase and 12% Basic Attack DMG Bonus to the wielder for 14s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"atkPct","label":"ATK%","value":12,"conditional":true},{"stat":"dmgBonus","label":"Basic DMG","value":12,"conditional":true,"appliesTo":["basic"]}], icon: "icons/weapons/boson-astrolabe.webp" },
    { id: "cosmic-ripples", name: "Cosmic Ripples", weaponType: "Rectifier", rarity: 5, baseAtk: 500, secondaryStat: "ATK%", secondaryValue: 54, passive: "Increases Energy Regen by 12.8%. When dealing Basic Attack DMG, increases Basic Attack DMG Bonus by 3.2%, stacking up to 5 time(s). This effect lasts for 8s and can be triggered 1 time(s) every 0.5s.", selfBuffs: [{"stat":"energyRegen","label":"Energy Regen","value":12.8,"conditional":false},{"stat":"dmgBonus","label":"Basic DMG · 5 stacks","value":16,"conditional":true,"appliesTo":["basic"]}], icon: "icons/weapons/cosmic-ripples.webp" },
    { id: "daybreakers-spine", name: "Daybreaker's Spine", weaponType: "Gauntlets", rarity: 5, baseAtk: 588, secondaryStat: "CRIT Rate", secondaryValue: 24.3, passive: "Increases ATK by 12%. After dealing Basic Attack DMG, the wielder gains 20% Spectro DMG Bonus for 4s. Each time after the wielder inflicts Tune Strain - Shifting on the target, they gain 20% Basic Attack DMG Amplification and their Basic Attack DMG ignores 10% of the target's DEF for 6s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"elemDmg","label":"Elem DMG","value":20,"conditional":true},{"stat":"dmgBonus","label":"Basic DMG","value":20,"conditional":true,"appliesTo":["basic"]},{"stat":"defIgnore","label":"DEF Ignore (Basic Atk)","value":10,"conditional":true,"appliesTo":["basic"]}], icon: "icons/weapons/daybreakers-spine.webp" },
    { id: "defiers-thorn", name: "Defier's Thorn", weaponType: "Sword", rarity: 5, baseAtk: 413, secondaryStat: "HP%", secondaryValue: 72.2, passive: "Max HP is increased by 12%. 15s after casting Intro Skill or Basic Attacks, ignore 8% of the target's DEF when dealing damage. If the target has at least 1 stack of Aero Erosion, the DMG taken by the target is Amplified by 20%.", selfBuffs: [{"stat":"hpPct","label":"HP%","value":12,"conditional":false},{"stat":"defIgnore","label":"DEF Ignore","value":8,"conditional":true,"autoTrigger":{"skillIds":["intro","basic"],"durationSeconds":15}}], icon: "icons/weapons/defiers-thorn.webp" },
    { id: "emerald-of-genesis", name: "Emerald of Genesis", weaponType: "Sword", rarity: 5, baseAtk: 588, secondaryStat: "CRIT Rate", secondaryValue: 24.3, passive: "Increases Energy Regen by 12.8%. When Resonance Skill is cast, increases ATK by 6%, stacking up to 2 time(s). This effect lasts for 10s.", selfBuffs: [{"stat":"energyRegen","label":"Energy Regen","value":12.8,"conditional":false},{"stat":"atkPct","label":"ATK% · 2 stacks","value":12,"conditional":true}], icon: "icons/weapons/emerald-of-genesis.webp" },
    { id: "emerald-sentence", name: "Emerald Sentence", weaponType: "Sword", rarity: 5, baseAtk: 588, secondaryStat: "CRIT Rate", secondaryValue: 24.3, passive: "ATK is increased by 12%. Casting Echo Skill within 10s after casting Intro Skill or Basic Attack grants 1 stack of Bamboo Cleaver, which grants 30% Heavy Attack DMG Bonus to the wielder. This effect can be triggered by Echoes of the same name once only, stacking up to 2 times, lasting for 12s. Casting Echo Skill at max stacks does not reset the duration. This effect can be triggered once every 10s and ends early if the wielder is switched off the field. Casting Intro Skill grants 20% Echo Skill DMG Bonus to all Resonators in the team for 30s. Effects of the same name cannot be stacked.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Heavy DMG · Bamboo Cleaver, 2 stacks","value":60,"conditional":true,"appliesTo":["heavy"]}], buffs: [{"stat":"dmgBonus","label":"Echo Skill DMG","value":20,"appliesTo":["echo"],"autoTrigger":{"skillIds":["intro"],"durationSeconds":30}}], icon: "icons/weapons/emerald-sentence.webp" },
    { id: "everbright-polestar", name: "Everbright Polestar", weaponType: "Sword", rarity: 5, baseAtk: 588, secondaryStat: "CRIT Rate", secondaryValue: 24.3, passive: "Increases All-Attribute DMG Bonus by 12%. When inflicting Tune Rupture - Shifting or Fusion Burst, the wielder's Resonance Liberation DMG ignores 32% DEF and 10% Fusion RES on targets for 8s.", selfBuffs: [{"stat":"elemDmg","label":"DMG Bonus","value":12,"conditional":false}], icon: "icons/weapons/everbright-polestar.webp" },
    { id: "kumokiri", name: "Kumokiri", weaponType: "Broadblade", rarity: 5, baseAtk: 500, secondaryStat: "CRIT Rate", secondaryValue: 36, passive: "ATK is increased by 12%. When the wielder casts Intro Skill or inflicts Negative Statuses, they gain 8% Resonance Liberation DMG Bonus, stacking up to 3 times for 15s. At max stacks, when Resonators in the team inflict Negative Statuses, they gain 24% All-Attribute DMG Bonus for 15s. Effects of the same name cannot be stacked.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Liberation DMG · 3 stacks","value":24,"conditional":true,"appliesTo":["ult"]},{"stat":"elemDmg","label":"DMG Bonus","value":24,"conditional":true}], icon: "icons/weapons/kumokiri.webp" },
    { id: "laser-shearer", name: "Laser Shearer", weaponType: "Sword", rarity: 5, baseAtk: 588, secondaryStat: "Energy Regen", secondaryValue: 38.9, passive: "Increases ATK by 12%. Dealing damage to targets under Tune Strain - Interfered grants 24% Resonance Skill Bonus for 3s. Retriggering the effect resets its duration.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Res. Skill DMG","value":24,"conditional":true,"appliesTo":["skill"]}], icon: "icons/weapons/laser-shearer.webp" },
    { id: "lethean-elegy", name: "Lethean Elegy", weaponType: "Rectifier", rarity: 5, baseAtk: 588, secondaryStat: "CRIT Rate", secondaryValue: 24.3, passive: "ATK is increased by 12%. Within 12s after dealing Echo Skill DMG, gain 32% Resonance Skill DMG Bonus and 32% Echo Skill DMG Amplification, and ignore 8% of the target's DEF when dealing damage.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Res. Skill DMG","value":32,"conditional":true,"appliesTo":["skill"]},{"stat":"dmgBonus","label":"Echo Skill DMG","value":32,"conditional":true,"appliesTo":["echo"]}], icon: "icons/weapons/lethean-elegy.webp" },
    { id: "luminous-hymn", name: "Luminous Hymn", weaponType: "Rectifier", rarity: 5, baseAtk: 500, secondaryStat: "CRIT Rate", secondaryValue: 36, passive: "Increase ATK by 12%. Dealing DMG to targets with Spectro Frazzle grants the wielder 14% Basic Attack DMG Bonus and 14% Heavy Attack DMG Bonus, stacking up to 3 times for 6s. Casting Outro Skill Amplifies the Spectro Frazzle DMG on targets around the active Resonator by 30% for 30s. Effects of the same name cannot be stacked.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Basic DMG · 3 stacks","value":42,"conditional":true,"appliesTo":["basic"]},{"stat":"dmgBonus","label":"Heavy DMG · 3 stacks","value":42,"conditional":true,"appliesTo":["heavy"]}], icon: "icons/weapons/luminous-hymn.webp" },
    { id: "lustrous-razor", name: "Lustrous Razor", weaponType: "Broadblade", rarity: 5, baseAtk: 588, secondaryStat: "ATK%", secondaryValue: 36.5, passive: "Increases Energy Regen by 12.8%. When Resonance Skill is cast, Resonance Liberation DMG Bonus is increased by 7%, stacking up to 3 times. This effect lasts for 12s.", selfBuffs: [{"stat":"energyRegen","label":"Energy Regen","value":12.8,"conditional":false},{"stat":"dmgBonus","label":"Liberation DMG · 3 stacks","value":21,"conditional":true,"appliesTo":["ult"]}], icon: "icons/weapons/lustrous-razor.webp" },
    { id: "lux-umbra", name: "Lux & Umbra", weaponType: "Pistols", rarity: 5, baseAtk: 588, secondaryStat: "CRIT DMG", secondaryValue: 48.6, passive: "ATK is increased by 12%. Upon dealing Echo Skill DMG, gain 24% Heavy Attack DMG Amplification for 6s. Upon dealing Heavy Attack DMG, gain 24% Echo Skill DMG Amplification for 6s. DMG Amplification on each attack is capped at 24%. While both effects are active, dealing damage ignores 8% of the target's DEF.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Heavy DMG","value":24,"conditional":true,"appliesTo":["heavy"]},{"stat":"dmgBonus","label":"Echo Skill DMG","value":24,"conditional":true,"appliesTo":["echo"],"autoTrigger":{"skillIds":["heavy"],"durationSeconds":6}}], icon: "icons/weapons/lux-umbra.webp" },
    { id: "moongazers-sigil", name: "Moongazer's Sigil", weaponType: "Gauntlets", rarity: 5, baseAtk: 500, secondaryStat: "CRIT Rate", secondaryValue: 36, passive: "Increases ATK by 12%. Casting Intro Skill or Resonance Liberation increases Resonance Liberation DMG by 20% for 15s. Obtaining Shield allows Resonance Liberation DMG to ignore 7.2% of the target's DEF for 7s, stacking up to 5 times. This effect is triggered once every 0.5s. Upon casting Intro Skill, this effect reaches max stacks immediately, lasting for 3s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Liberation DMG","value":20,"conditional":true,"appliesTo":["ult"],"autoTrigger":{"skillIds":["intro","ult"],"durationSeconds":15}}], icon: "icons/weapons/moongazers-sigil.webp" },
    { id: "phasic-homogenizer", name: "Phasic Homogenizer", weaponType: "Pistols", rarity: 5, baseAtk: 588, secondaryStat: "CRIT DMG", secondaryValue: 48.6, passive: "Increases ATK by 12%. After a Resonator in the team casts a Tune Break skill, it grants 20% All-Attribute DMG Bonus to the wielder for 14s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"elemDmg","label":"DMG Bonus","value":20,"conditional":true}], icon: "icons/weapons/phasic-homogenizer.webp" },
    { id: "pulsation-bracer", name: "Pulsation Bracer", weaponType: "Gauntlets", rarity: 5, baseAtk: 588, secondaryStat: "CRIT Rate", secondaryValue: 24.3, passive: "Increases ATK by 12%. Dealing damage to targets under Tune Strain - Interfered grants 6% Basic Attack DMG Bonus for 3s, stacking up to 4 times. This effect can be triggered 1 time(s) every 0.5s. Retriggering the effect resets its duration.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Basic DMG · 4 stacks","value":24,"conditional":true,"appliesTo":["basic"]}], icon: "icons/weapons/pulsation-bracer.webp" },
    { id: "radiance-cleaver", name: "Radiance Cleaver", weaponType: "Broadblade", rarity: 5, baseAtk: 588, secondaryStat: "CRIT DMG", secondaryValue: 48.6, passive: "Increases ATK by 12%. Dealing damage to targets under Tune Strain - Interfered grants 24% Resonance Liberation Bonus for 3s. Retriggering the effect resets its duration.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Liberation DMG","value":24,"conditional":true,"appliesTo":["ult"]}], icon: "icons/weapons/radiance-cleaver.webp" },
    { id: "red-spring", name: "Red Spring", weaponType: "Sword", rarity: 5, baseAtk: 588, secondaryStat: "CRIT Rate", secondaryValue: 24.3, passive: "Increase ATK by 12%. When dealing Basic Attack DMG, the wielder gains 10% Basic Attack DMG Bonus for 14s. This effect can be triggered once per second, stacking up to 3 times. When the wielder's Concerto Energy is consumed, gain 40% Basic DMG Bonus for 10. This effect can be triggered once per second and ends when the wielder is switched off the field.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Basic DMG · 3 stacks","value":30,"conditional":true,"appliesTo":["basic"]},{"stat":"dmgBonus","label":"Basic DMG · Concerto Energy consumed","value":40,"conditional":true,"appliesTo":["basic"]}], icon: "icons/weapons/red-spring.webp" },
    { id: "rime-draped-sprouts", name: "Rime-Draped Sprouts", weaponType: "Rectifier", rarity: 5, baseAtk: 500, secondaryStat: "CRIT DMG", secondaryValue: 72, passive: "Increase ATK by 12%. While the wielder is on the field, using Resonance Skill grants 12% Basic Attack DMG Bonus, stacking up to 3 times for 6s. At 3 stacks or above, casting Outro Skill consumes all stacks of this effect and grants the wielder 52% Basic Attack DMG Bonus for 27s, effective when the wielder is off the field.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Basic DMG · 3 stacks","value":36,"conditional":true,"appliesTo":["basic"]},{"stat":"dmgBonus","label":"Basic DMG · Outro payoff (off-field)","value":52,"conditional":true,"appliesTo":["basic"]}], icon: "icons/weapons/rime-draped-sprouts.webp" },
    { id: "spectrum-blaster", name: "Spectrum Blaster", weaponType: "Pistols", rarity: 5, baseAtk: 588, secondaryStat: "CRIT Rate", secondaryValue: 24.3, passive: "Increases ATK by 12%. Casting Intro Skill or dealing Basic Attack DMG to targets increases the wielder's Basic Attack DMG Bonus by 36% for 4s. Each time the wielder inflicts Tune Rupture - Shifting or Tune Strain - Shifting during Basic Attacks, all DMG dealt by Resonators in the team is increased by 8% for 30s, up to 3 stacks. Effects of the same name cannot be stacked.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Basic DMG","value":36,"conditional":true,"appliesTo":["basic"],"autoTrigger":{"skillIds":["intro","basic"],"durationSeconds":4}}], buffs: [{"stat":"elemDmg","label":"All DMG · 3 stacks","value":24}], icon: "icons/weapons/spectrum-blaster.webp" },
    { id: "starfield-calibrator", name: "Starfield Calibrator", weaponType: "Broadblade", rarity: 5, baseAtk: 413, secondaryStat: "Energy Regen", secondaryValue: 77, passive: "Increases DEF by 16%. Casting Resonance Skill restores 8 points of Concerto Energy. This effect can be triggered 1 time(s) every 20s. When the wielder heals Resonators, increases Crit. DMG of all nearby Resonators in the team by 20% for 4s. Effects of the same name cannot be stacked.", selfBuffs: [{"stat":"defPct","label":"DEF%","value":16,"conditional":false}], buffs: [{"stat":"critDmg","label":"Crit DMG","value":20}], icon: "icons/weapons/starfield-calibrator.webp" },
    { id: "static-mist", name: "Static Mist", weaponType: "Pistols", rarity: 5, baseAtk: 588, secondaryStat: "CRIT Rate", secondaryValue: 24.3, passive: "Increases Energy Regen by 12.8%. Incoming Resonator's ATK is increased by 10% for 14s, stackable for up to 1 times after the wielder casts Outro Skill.", selfBuffs: [{"stat":"energyRegen","label":"Energy Regen","value":12.8,"conditional":false},{"stat":"atkPct","label":"ATK%","value":10,"conditional":true}], icon: "icons/weapons/static-mist.webp" },
    { id: "stellar-symphony", name: "Stellar Symphony", weaponType: "Rectifier", rarity: 5, baseAtk: 413, secondaryStat: "Energy Regen", secondaryValue: 77, passive: "Increase HP by 12%. Restore 8 Concerto Energy when casting Resonance Liberation. This effect can be triggered 1 time(s) every 20s. When casting Resonance Skill that heals, increase nearby party members' ATK by 14% for 30s. Effects of the same name cannot be stacked.", selfBuffs: [{"stat":"hpPct","label":"HP%","value":12,"conditional":false},{"stat":"atkPct","label":"ATK%","value":14,"conditional":true}], icon: "icons/weapons/stellar-symphony.webp" },
    { id: "stringmaster", name: "Stringmaster", weaponType: "Rectifier", rarity: 5, baseAtk: 500, secondaryStat: "CRIT Rate", secondaryValue: 36, passive: "Grants 12% Attribute DMG Bonus. When dealing Resonance Skill DMG, increases ATK by 12%, stacking up to 2 times. This effect lasts for 5s. When the wielder is not on the field, increases their ATK by an additional 12%.", selfBuffs: [{"stat":"elemDmg","label":"DMG Bonus","value":12,"conditional":false},{"stat":"atkPct","label":"ATK% · 2 stacks","value":24,"conditional":true},{"stat":"atkPct","label":"ATK% · off-field bonus","value":12,"conditional":true}], icon: "icons/weapons/stringmaster.webp" },
    { id: "the-last-dance", name: "The Last Dance", weaponType: "Pistols", rarity: 5, baseAtk: 500, secondaryStat: "CRIT DMG", secondaryValue: 72, passive: "Increases ATK by 12%. Every time Intro Skill or Resonance Liberation is cast, Resonance Skill DMG Bonus increases by 48% for 5s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Res. Skill DMG","value":48,"conditional":true,"appliesTo":["skill"],"autoTrigger":{"skillIds":["intro","ult"],"durationSeconds":5}}], icon: "icons/weapons/the-last-dance.webp" },
    { id: "thunderflare-dominion", name: "Thunderflare Dominion", weaponType: "Broadblade", rarity: 5, baseAtk: 675, secondaryStat: "CRIT Rate", secondaryValue: 12.2, passive: "Increases ATK by 12%. Casting Intro Skill or Resonance Skill increases Heavy Attack DMG by 20% for 15s. Obtaining Shield allows Heavy Attack DMG to ignore 7.2% of the target's DEF for 7s, stacking up to 5 times. This effect is triggered once every 0.5s", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Heavy DMG","value":20,"conditional":true,"appliesTo":["heavy"],"autoTrigger":{"skillIds":["intro","skill"],"durationSeconds":15}}], icon: "icons/weapons/thunderflare-dominion.webp" },
    { id: "tragicomedy", name: "Tragicomedy", weaponType: "Gauntlets", rarity: 5, baseAtk: 588, secondaryStat: "CRIT Rate", secondaryValue: 24.3, passive: "Increases ATK by 12%. Every time Basic Attack or Intro Skill is cast, Heavy Attack DMG Bonus increases by 48% for 3s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Heavy DMG","value":48,"conditional":true,"appliesTo":["heavy"],"autoTrigger":{"skillIds":["basic","intro"],"durationSeconds":3}}], icon: "icons/weapons/tragicomedy.webp" },
    { id: "unflickering-valor", name: "Unflickering Valor", weaponType: "Sword", rarity: 5, baseAtk: 413, secondaryStat: "Energy Regen", secondaryValue: 77, passive: "Increase Crit. Rate by 8%. Casting Resonance Liberation gives 24% Basic Attack DMG Bonus for 10s. Dealing Basic Attack DMG gives 24% Basic Attack DMG Bonus for 4s.", selfBuffs: [{"stat":"critRate","label":"Crit Rate","value":8,"conditional":false},{"stat":"dmgBonus","label":"Basic DMG · on Liberation cast","value":24,"conditional":true,"appliesTo":["basic"],"autoTrigger":{"skillIds":["ult"],"durationSeconds":10}},{"stat":"dmgBonus","label":"Basic DMG · on Basic Attack hit","value":24,"conditional":true,"appliesTo":["basic"],"autoTrigger":{"skillIds":["basic"],"durationSeconds":4}}], icon: "icons/weapons/unflickering-valor.webp" },
    { id: "verdant-summit", name: "Verdant Summit", weaponType: "Broadblade", rarity: 5, baseAtk: 588, secondaryStat: "CRIT DMG", secondaryValue: 48.6, passive: "Increases Attribute DMG Bonus by 12%. Every time Intro Skill or Resonance Liberation is cast, increases Heavy Attack DMG Bonus by 24%, stacking up to 2 time(s). This effect lasts for 14s.", selfBuffs: [{"stat":"elemDmg","label":"DMG Bonus","value":12,"conditional":false},{"stat":"dmgBonus","label":"Heavy DMG · 2 stacks","value":48,"conditional":true,"appliesTo":["heavy"]}], icon: "icons/weapons/verdant-summit.webp" },
    { id: "veritys-handle", name: "Verity's Handle", weaponType: "Gauntlets", rarity: 5, baseAtk: 588, secondaryStat: "CRIT Rate", secondaryValue: 24.3, passive: "Gain 12% Attribute DMG Bonus. When using Resonance Liberation, the wielder gains 48% Resonance Liberation DMG Bonus for 8s. This effect can be extended by 5s each time Resonance Skills are cast, up to 3 times.", selfBuffs: [{"stat":"elemDmg","label":"DMG Bonus","value":12,"conditional":false},{"stat":"dmgBonus","label":"Liberation DMG","value":48,"conditional":true,"appliesTo":["ult"]}], icon: "icons/weapons/veritys-handle.webp" },
    { id: "whispers-of-sirens", name: "Whispers of Sirens", weaponType: "Rectifier", rarity: 5, baseAtk: 500, secondaryStat: "CRIT DMG", secondaryValue: 72, passive: "Increases ATK by 12%. Casting Echo Skill within 10s after casting Intro Skill or Basic Attacks grants 1 stack of Gentle Dream. Echoes with the same name can only trigger this effect once, stacking up to 2 times, lasting for 10s. When reaching 2 stacks, casting Echo Skill no longer resets the duration of this effect. This effect activates up to once per 10s. Switching to another Resonator ends this effect early. With 1 stack: Grants 40% Basic Attack DMG Bonus. With 2 stacks: Ignores 12% of the target's Havoc RES.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Basic DMG","value":40,"conditional":true,"appliesTo":["basic"]}], icon: "icons/weapons/whispers-of-sirens.webp" },
    { id: "wildfire-mark", name: "Wildfire Mark", weaponType: "Broadblade", rarity: 5, baseAtk: 588, secondaryStat: "CRIT DMG", secondaryValue: 48.6, passive: "Increases ATK by 12%. Performing Intro Skill or Resonance Liberation increases Resonance Liberation DMG by 24% for 6s. Dealing Heavy Attack DMG extends this effect by 4s, up to 1 time. Each successful extension gives 24% Fusion DMG Bonus to all Resonators in the team for 30s. Effects of the same name cannot be stacked.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Liberation DMG","value":24,"conditional":true,"appliesTo":["ult"]},{"stat":"elemDmg","label":"Elem DMG","value":24,"conditional":true}], icon: "icons/weapons/wildfire-mark.webp" },
    { id: "woodland-aria", name: "Woodland Aria", weaponType: "Pistols", rarity: 5, baseAtk: 500, secondaryStat: "CRIT Rate", secondaryValue: 36, passive: "ATK is increased by 12%. Inflicting Aero Erosion on the target gives 24% Aero DMG Bonus for 10s. Hitting targets with Aero Erosion reduces their Aero RES by 10% for 20s. Effects of the same name cannot be stacked.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"elemDmg","label":"Aero DMG Bonus","value":24,"conditional":true},{"stat":"elemDmg","label":"Aero DMG · RES shred","value":10,"conditional":true}], icon: "icons/weapons/woodland-aria.webp" },
    { id: "aether-strike", name: "Aether Strike", weaponType: "Gauntlets", rarity: 4, baseAtk: 413, secondaryStat: "CRIT DMG", secondaryValue: 40.5, passive: "Casting Resonance Liberation increases ATK by 7.2% and grants 10.8% Resonance Liberation DMG Bonus for 15s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":7.2,"conditional":true,"autoTrigger":{"skillIds":["ult"],"durationSeconds":15}},{"stat":"dmgBonus","label":"Liberation DMG","value":10.8,"conditional":true,"appliesTo":["ult"],"autoTrigger":{"skillIds":["ult"],"durationSeconds":15}}], icon: "icons/weapons/aether-strike.webp" },
    { id: "amity-accord", name: "Amity Accord", weaponType: "Gauntlets", rarity: 4, baseAtk: 338, secondaryStat: "DEF%", secondaryValue: 61.6, passive: "When Intro Skill is cast, increases Resonance Liberation DMG Bonus by 20%, lasting for 15s.", selfBuffs: [{"stat":"dmgBonus","label":"Liberation DMG","value":20,"conditional":true,"appliesTo":["ult"],"autoTrigger":{"skillIds":["intro"],"durationSeconds":15}}], icon: "icons/weapons/amity-accord.webp" },
    { id: "augment", name: "Augment", weaponType: "Rectifier", rarity: 4, baseAtk: 413, secondaryStat: "CRIT Rate", secondaryValue: 20.3, passive: "Casting Resonance Liberation increases the wielder's ATK by 15%, lasting for 15s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":15,"conditional":true,"autoTrigger":{"skillIds":["ult"],"durationSeconds":15}}], icon: "icons/weapons/augment.webp" },
    { id: "aureate-zenith", name: "Aureate Zenith", weaponType: "Broadblade", rarity: 4, baseAtk: 413, secondaryStat: "CRIT DMG", secondaryValue: 40.5, passive: "Casting Resonance Liberation increases ATK by 7.2% and grants 10.8% Heavy Attack DMG Bonus for 15s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":7.2,"conditional":true,"autoTrigger":{"skillIds":["ult"],"durationSeconds":15}},{"stat":"dmgBonus","label":"Heavy DMG","value":10.8,"conditional":true,"appliesTo":["heavy"],"autoTrigger":{"skillIds":["ult"],"durationSeconds":15}}], icon: "icons/weapons/aureate-zenith.webp" },
    { id: "autumntrace", name: "Autumntrace", weaponType: "Broadblade", rarity: 4, baseAtk: 413, secondaryStat: "CRIT Rate", secondaryValue: 20.3, passive: "Increases ATK by 4% upon dealing Basic Attack DMG or Heavy Attack DMG, stacking up to 5 time(s). This effect lasts for 7s and can be triggered 1 time(s) every 1s.", selfBuffs: [{"stat":"atkPct","label":"ATK% · 5 stacks","value":20,"conditional":true}], icon: "icons/weapons/autumntrace.webp" },
    { id: "broadblade-41", name: "Broadblade#41", weaponType: "Broadblade", rarity: 4, baseAtk: 413, secondaryStat: "Energy Regen", secondaryValue: 32.4, passive: "When the Resonator's HP is above 80%, increases ATK by 12%. When the Resonator's HP is below 40%, gives 5% healing when dealing Basic Attack DMG or Heavy Attack DMG. This effect can be triggered 1 time(s) every 8s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":true}], icon: "icons/weapons/broadblade-41.webp" },
    { id: "cadenza", name: "Cadenza", weaponType: "Pistols", rarity: 4, baseAtk: 338, secondaryStat: "Energy Regen", secondaryValue: 51.8, passive: "When Resonance Skill is cast, restores 8 Concerto Energy. This effect can be triggered 1 times every 20s.", icon: "icons/weapons/cadenza.webp" },
    { id: "call-of-the-abyss", name: "Call of the Abyss", weaponType: "Rectifier", rarity: 4, baseAtk: 338, secondaryStat: "Energy Regen", secondaryValue: 51.8, passive: "Casting Resonance Liberation increases the Resonator's Healing Bonus by 16% for 15s.", selfBuffs: [{"stat":"healingBonus","label":"Healing Bonus","value":16,"conditional":true,"autoTrigger":{"skillIds":["ult"],"durationSeconds":15}}], icon: "icons/weapons/call-of-the-abyss.webp" },
    { id: "celestial-spiral", name: "Celestial Spiral", weaponType: "Gauntlets", rarity: 4, baseAtk: 463, secondaryStat: "ATK%", secondaryValue: 18.2, passive: "Casting the Resonance Skill grants 6 Resonance Energy and increases ATK by 10%, lasting for 16s. This effect can be triggered once every 20s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":10,"conditional":true,"autoTrigger":{"skillIds":["skill"],"durationSeconds":16}}], icon: "icons/weapons/celestial-spiral.webp" },
    { id: "comet-flare", name: "Comet Flare", weaponType: "Rectifier", rarity: 4, baseAtk: 413, secondaryStat: "HP%", secondaryValue: 30.4, passive: "When dealing Basic Attack DMG or Heavy Attack DMG, increases Healing Bonus by 3%, stacking up to 3 time(s). This effect lasts for 8s and can be triggered 1 time(s) every 0.6s.", selfBuffs: [{"stat":"healingBonus","label":"Healing Bonus · 3 stacks","value":9,"conditional":true}], icon: "icons/weapons/comet-flare.webp" },
    { id: "commando-of-conviction", name: "Commando of Conviction", weaponType: "Sword", rarity: 4, baseAtk: 413, secondaryStat: "ATK%", secondaryValue: 30.4, passive: "When Intro Skill is cast, increases ATK by 15%, lasting for 15s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":15,"conditional":true,"autoTrigger":{"skillIds":["intro"],"durationSeconds":15}}], icon: "icons/weapons/commando-of-conviction.webp" },
    { id: "dauntless-evernight", name: "Dauntless Evernight", weaponType: "Broadblade", rarity: 4, baseAtk: 338, secondaryStat: "DEF%", secondaryValue: 61.6, passive: "When Intro Skill is cast, increases ATK by 8% and DEF by 15%, lasting for 15s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":8,"conditional":true,"autoTrigger":{"skillIds":["intro"],"durationSeconds":15}},{"stat":"defPct","label":"DEF%","value":15,"conditional":true,"autoTrigger":{"skillIds":["intro"],"durationSeconds":15}}], icon: "icons/weapons/dauntless-evernight.webp" },
    { id: "discord", name: "Discord", weaponType: "Broadblade", rarity: 4, baseAtk: 338, secondaryStat: "Energy Regen", secondaryValue: 51.8, passive: "When Resonance Skill is cast, restores 8 Concerto Energy. This effect can be triggered 1 time(s) every 20s.", icon: "icons/weapons/discord.webp" },
    { id: "endless-collapse", name: "Endless Collapse", weaponType: "Sword", rarity: 4, baseAtk: 463, secondaryStat: "ATK%", secondaryValue: 18.2, passive: "Casting the Resonance Skill grants 6 Resonance Energy and increases ATK by 10%, lasting for 16s. This effect can be triggered once every 20s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":10,"conditional":true,"autoTrigger":{"skillIds":["skill"],"durationSeconds":16}}], icon: "icons/weapons/endless-collapse.webp" },
    { id: "fables-of-wisdom", name: "Fables of Wisdom", weaponType: "Sword", rarity: 4, baseAtk: 463, secondaryStat: "ATK%", secondaryValue: 18.2, passive: "Dealing DMG to enemies with Negative Statuses increases the wielder's ATK by 4% for 10s. This effect can be triggered 1 time per second, stackable up to 4 times.", selfBuffs: [{"stat":"atkPct","label":"ATK% · 4 stacks","value":16,"conditional":true}], icon: "icons/weapons/fables-of-wisdom.webp" },
    { id: "feather-edge", name: "Feather Edge", weaponType: "Sword", rarity: 4, baseAtk: 413, secondaryStat: "CRIT Rate", secondaryValue: 20.3, passive: "Casting Resonance Liberation increases ATK by 7.2% and grants 10.8% Resonance Liberation DMG Bonus for 15s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":7.2,"conditional":true,"autoTrigger":{"skillIds":["ult"],"durationSeconds":15}},{"stat":"dmgBonus","label":"Liberation DMG","value":10.8,"conditional":true,"appliesTo":["ult"],"autoTrigger":{"skillIds":["ult"],"durationSeconds":15}}], icon: "icons/weapons/feather-edge.webp" },
    { id: "fusion-accretion", name: "Fusion Accretion", weaponType: "Rectifier", rarity: 4, baseAtk: 463, secondaryStat: "ATK%", secondaryValue: 18.2, passive: "Casting the Resonance Skill grants 6 Resonance Energy and increases ATK by 10%, lasting for 16s. This effect can be triggered once every 20s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":10,"conditional":true,"autoTrigger":{"skillIds":["skill"],"durationSeconds":16}}], icon: "icons/weapons/fusion-accretion.webp" },
    { id: "gauntlets-21d", name: "Gauntlets#21D", weaponType: "Gauntlets", rarity: 4, baseAtk: 388, secondaryStat: "Energy Regen", secondaryValue: 38.9, passive: "When the Resonator dashes or dodges, increases ATK by 8%. Increases Dodge Counter DMG by 50%, lasting for 8s. When Dodge Counter is performed, heals 5% of the Resonator's Max HP. This effect can be triggered 1 time(s) every 6s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":8,"conditional":true}], icon: "icons/weapons/gauntlets-21d.webp" },
    { id: "helios-cleaver", name: "Helios Cleaver", weaponType: "Broadblade", rarity: 4, baseAtk: 413, secondaryStat: "ATK%", secondaryValue: 30.4, passive: "Within 12s after Resonance Skill is cast, increases ATK by 3% every 2s, stacking up to 4 time(s). This effect can be triggered 1 time(s) every 12s. When the number of stacks reaches 4, all stacks will be reset within 6s.", selfBuffs: [{"stat":"atkPct","label":"ATK% · 4 stacks","value":12,"conditional":true}], icon: "icons/weapons/helios-cleaver.webp" },
    { id: "hollow-mirage", name: "Hollow Mirage", weaponType: "Gauntlets", rarity: 4, baseAtk: 413, secondaryStat: "ATK%", secondaryValue: 30.4, passive: "When Resonance Liberation is cast, grants 3 stack(s) of Iron Armor. Each stack increases ATK and DEF by 3%, stacking up to 3 time(s). When the Resonator takes damage, reduces the number of stacks by 1.", selfBuffs: [{"stat":"defPct","label":"DEF% · 3 stacks","value":9,"conditional":true},{"stat":"atkPct","label":"ATK% · 3 stacks","value":9,"conditional":true}], icon: "icons/weapons/hollow-mirage.webp" },
    { id: "jinzhou-keeper", name: "Jinzhou Keeper", weaponType: "Rectifier", rarity: 4, baseAtk: 388, secondaryStat: "ATK%", secondaryValue: 36.5, passive: "Casting Intro Skill increases the wielder's ATK by 8% and HP by 10%, lasting for 15s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":8,"conditional":true,"autoTrigger":{"skillIds":["intro"],"durationSeconds":15}},{"stat":"hpPct","label":"HP%","value":10,"conditional":true,"autoTrigger":{"skillIds":["intro"],"durationSeconds":15}}], icon: "icons/weapons/jinzhou-keeper.webp" },
    { id: "legend-of-drunken-hero", name: "Legend of Drunken Hero", weaponType: "Gauntlets", rarity: 4, baseAtk: 463, secondaryStat: "ATK%", secondaryValue: 18.2, passive: "Dealing DMG to enemies with Negative Statuses increases the wielder's ATK by 4% for 10s. This effect can be triggered 1 time per second, stackable up to 4 times.", selfBuffs: [{"stat":"atkPct","label":"ATK% · 4 stacks","value":16,"conditional":true}], icon: "icons/weapons/legend-of-drunken-hero.webp" },
    { id: "lumingloss", name: "Lumingloss", weaponType: "Sword", rarity: 4, baseAtk: 388, secondaryStat: "ATK%", secondaryValue: 36.5, passive: "When Resonance Skill is cast, increases Basic Attack DMG Bonus and Heavy Attack DMG Bonus by 20%, stacking up to 1 time(s). This effect lasts for 10s and can be triggered 1 time(s) every 1s.", selfBuffs: [{"stat":"dmgBonus","label":"Heavy DMG","value":20,"conditional":true,"appliesTo":["heavy"],"autoTrigger":{"skillIds":["skill"],"durationSeconds":10}},{"stat":"dmgBonus","label":"Basic DMG","value":20,"conditional":true,"appliesTo":["basic"],"autoTrigger":{"skillIds":["skill"],"durationSeconds":10}}], icon: "icons/weapons/lumingloss.webp" },
    { id: "lunar-cutter", name: "Lunar Cutter", weaponType: "Sword", rarity: 4, baseAtk: 413, secondaryStat: "ATK%", secondaryValue: 30.4, passive: "Equipped Resonator gains 6 stack(s) of Oath upon entering the battlefield. Each stack increases ATK by 2%, up to 6 stacks. This effect can be triggered 1 time(s) every 12s. The equipped Resonator loses 1 stack(s) of Oath every 2s, and gains 6 stack(s) upon defeating an enemy.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":2,"conditional":true}], icon: "icons/weapons/lunar-cutter.webp" },
    { id: "marcato", name: "Marcato", weaponType: "Gauntlets", rarity: 4, baseAtk: 338, secondaryStat: "Energy Regen", secondaryValue: 51.8, passive: "When Resonance Skill is cast, restores 8 Concerto Energy. This effect can be triggered 1 times every 20s.", icon: "icons/weapons/marcato.webp" },
    { id: "meditations-on-mercy", name: "Meditations on Mercy", weaponType: "Broadblade", rarity: 4, baseAtk: 463, secondaryStat: "ATK%", secondaryValue: 18.2, passive: "Dealing DMG to enemies with Negative Statuses increases the wielder's ATK by 4% for 10s. This effect can be triggered 1 time per second, stackable up to 4 times.", selfBuffs: [{"stat":"atkPct","label":"ATK% · 4 stacks","value":16,"conditional":true}], icon: "icons/weapons/meditations-on-mercy.webp" },
    { id: "novaburst", name: "Novaburst", weaponType: "Pistols", rarity: 4, baseAtk: 413, secondaryStat: "ATK%", secondaryValue: 30.4, passive: "When the Resonator dashes or dodges, increases ATK by 4%, stacking up to 3 time(s). This effect lasts for 8s.", selfBuffs: [{"stat":"atkPct","label":"ATK% · 3 stacks","value":12,"conditional":true}], icon: "icons/weapons/novaburst.webp" },
    { id: "oceans-gift", name: "Ocean's Gift", weaponType: "Rectifier", rarity: 4, baseAtk: 463, secondaryStat: "ATK%", secondaryValue: 18.2, passive: "Dealing DMG to enemies with Spectro Frazzle increases the wielder's Spectro DMG by 6%, gaining 1 stack per second for 6s, stacking up to 4 times.", selfBuffs: [{"stat":"elemDmg","label":"Elem DMG · 4 stacks","value":24,"conditional":true}], icon: "icons/weapons/oceans-gift.webp" },
    { id: "overture", name: "Overture", weaponType: "Sword", rarity: 4, baseAtk: 338, secondaryStat: "Energy Regen", secondaryValue: 51.8, passive: "When Resonance Skill is cast, restores 8 Concerto Energy. This effect can be triggered 1 time(s) every 20s.", icon: "icons/weapons/overture.webp" },
    { id: "pistols-26", name: "Pistols#26", weaponType: "Pistols", rarity: 4, baseAtk: 388, secondaryStat: "ATK%", secondaryValue: 36.5, passive: "When the Resonator takes no damage, increases ATK by 6% every 5s, stacking up to 2 time(s). This effect lasts for 8s. When the Resonator takes damage, loses 1 stacks and heals 5% of their Max HP.", selfBuffs: [{"stat":"atkPct","label":"ATK% · 2 stacks","value":12,"conditional":true}], icon: "icons/weapons/pistols-26.webp" },
    { id: "radiant-dawn", name: "Radiant Dawn", weaponType: "Rectifier", rarity: 4, baseAtk: 413, secondaryStat: "CRIT DMG", secondaryValue: 40.5, passive: "Casting Resonance Skill increases ATK by 9% and grants 9% Basic Attack DMG Bonus for 10s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":9,"conditional":true,"autoTrigger":{"skillIds":["skill"],"durationSeconds":10}}], icon: "icons/weapons/radiant-dawn.webp" },
    { id: "rectifier-25", name: "Rectifier#25", weaponType: "Rectifier", rarity: 4, baseAtk: 338, secondaryStat: "Energy Regen", secondaryValue: 51.8, passive: "When Resonance Skill is cast, if the Resonator's HP is below 60%, heals 5% of their Max HP. This effect can be triggered 1 time(s) every 8s. If the Resonator's HP is above 60%, increases ATK by 12%, lasting for 10s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":true}], icon: "icons/weapons/rectifier-25.webp" },
    { id: "relativistic-jet", name: "Relativistic Jet", weaponType: "Pistols", rarity: 4, baseAtk: 463, secondaryStat: "ATK%", secondaryValue: 18.2, passive: "Casting the Resonance Skill grants 6 Resonance Energy and increases ATK by 10%, lasting for 16s. This effect can be triggered once every 20s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":10,"conditional":true,"autoTrigger":{"skillIds":["skill"],"durationSeconds":16}}], icon: "icons/weapons/relativistic-jet.webp" },
    { id: "romance-in-farewell", name: "Romance in Farewell", weaponType: "Pistols", rarity: 4, baseAtk: 463, secondaryStat: "ATK%", secondaryValue: 18.2, passive: "Dealing DMG to enemies with Negative Statuses increases the wielder's ATK by 4% for 10s. This effect can be triggered 1 time per second, stackable up to 4 times.", selfBuffs: [{"stat":"atkPct","label":"ATK% · 4 stacks","value":16,"conditional":true}], icon: "icons/weapons/romance-in-farewell.webp" },
    { id: "solar-flame", name: "Solar Flame", weaponType: "Pistols", rarity: 4, baseAtk: 413, secondaryStat: "CRIT Rate", secondaryValue: 20.3, passive: "Dealing Basic Attack or Heavy Attack DMG increases ATK by 2.2% and grants 2.2% Heavy Attack DMG Bonus for 7s, stacking up to 4 times. This effect can be triggered 1 time(s) every 1s.", selfBuffs: [{"stat":"atkPct","label":"ATK% · 4 stacks","value":8.8,"conditional":true}], icon: "icons/weapons/solar-flame.webp" },
    { id: "somnoire-anchor", name: "Somnoire Anchor", weaponType: "Sword", rarity: 4, baseAtk: 463, secondaryStat: "ATK%", secondaryValue: 18.2, passive: "Gain 1 stack of Hiss when dealing damage to the target, with 1 stack generated every 1s. Hiss: each stack increases the wielder's ATK by 2% for 3s, stacking up to 10 times. Switching off the wielder clears all stacks. Gaining 10 stacks increases the wielder's Crit. Rate by 6%.", selfBuffs: [{"stat":"atkPct","label":"ATK% · 10 stacks","value":20,"conditional":true},{"stat":"critRate","label":"Crit Rate","value":6,"conditional":true}], icon: "icons/weapons/somnoire-anchor.webp" },
    { id: "stonard", name: "Stonard", weaponType: "Gauntlets", rarity: 4, baseAtk: 413, secondaryStat: "CRIT Rate", secondaryValue: 20.3, passive: "Casting Resonance Skill increases the wielder's Resonance Liberation DMG Bonus by 18%, lasting for 15s.", selfBuffs: [{"stat":"dmgBonus","label":"Liberation DMG","value":18,"conditional":true,"appliesTo":["ult"],"autoTrigger":{"skillIds":["skill"],"durationSeconds":15}}], icon: "icons/weapons/stonard.webp" },
    { id: "sword-18", name: "Sword#18", weaponType: "Sword", rarity: 4, baseAtk: 388, secondaryStat: "ATK%", secondaryValue: 36.5, passive: "When the Resonator's HP drops below 40%, increases Heavy Attack DMG Bonus by 18% and gives 5% healing when dealing Heavy Attack DMG. This effect can be triggered 1 time(s) every 8s.", selfBuffs: [{"stat":"dmgBonus","label":"Heavy DMG","value":18,"conditional":true,"appliesTo":["heavy"]}], icon: "icons/weapons/sword-18.webp" },
    { id: "thunderbolt", name: "Thunderbolt", weaponType: "Pistols", rarity: 4, baseAtk: 388, secondaryStat: "ATK%", secondaryValue: 36.5, passive: "When hitting a target with Basic Attacks or Heavy Attacks, increases Resonance Skill DMG Bonus by 7%, stacking up to 3 time(s). This effect lasts for 10s and can be triggered 1 time(s) every 1s.", selfBuffs: [{"stat":"dmgBonus","label":"Res. Skill DMG · 3 stacks","value":21,"conditional":true,"appliesTo":["skill"]}], icon: "icons/weapons/thunderbolt.webp" },
    { id: "undying-flame", name: "Undying Flame", weaponType: "Pistols", rarity: 4, baseAtk: 413, secondaryStat: "ATK%", secondaryValue: 30.4, passive: "When Intro Skill is cast, increases Resonance Skill DMG Bonus by 20% for 15s.", selfBuffs: [{"stat":"dmgBonus","label":"Res. Skill DMG","value":20,"conditional":true,"appliesTo":["skill"],"autoTrigger":{"skillIds":["intro"],"durationSeconds":15}}], icon: "icons/weapons/undying-flame.webp" },
    { id: "variation", name: "Variation", weaponType: "Rectifier", rarity: 4, baseAtk: 338, secondaryStat: "Energy Regen", secondaryValue: 51.8, passive: "When Resonance Skill is cast, restores 8 Concerto Energy. This effect can be triggered 1 times every 20s.", icon: "icons/weapons/variation.webp" },
    { id: "waltz-in-masquerade", name: "Waltz in Masquerade", weaponType: "Rectifier", rarity: 4, baseAtk: 463, secondaryStat: "ATK%", secondaryValue: 18.2, passive: "Dealing DMG to enemies with Negative Statuses increases the wielder's ATK by 4% for 10s. This effect can be triggered 1 time per second, stackable up to 4 times.", selfBuffs: [{"stat":"atkPct","label":"ATK% · 4 stacks","value":16,"conditional":true}], icon: "icons/weapons/waltz-in-masquerade.webp" },
    { id: "waning-redshift", name: "Waning Redshift", weaponType: "Broadblade", rarity: 4, baseAtk: 463, secondaryStat: "ATK%", secondaryValue: 18.2, passive: "Casting the Resonance Skill grants 6 Resonance Energy and increases ATK by 10%, lasting for 16s. This effect can be triggered once every 20s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":10,"conditional":true,"autoTrigger":{"skillIds":["skill"],"durationSeconds":16}}], icon: "icons/weapons/waning-redshift.webp" },
    { id: "beguiling-melody", name: "Beguiling Melody", weaponType: "Broadblade", rarity: 3, baseAtk: 300, secondaryStat: "ATK%", secondaryValue: 30.4, passive: "When Intro Skill is cast, restores 4 Concerto Energy. When Outro Skill is cast, restores 4 Resonance Energy.", icon: "icons/weapons/beguiling-melody.webp" },
    { id: "broadblade-of-night", name: "Broadblade of Night", weaponType: "Broadblade", rarity: 3, baseAtk: 325, secondaryStat: "ATK%", secondaryValue: 24.3, passive: "When Intro Skill is cast, increases ATK by 8%, lasting for 10s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":8,"conditional":true,"autoTrigger":{"skillIds":["intro"],"durationSeconds":10}}], icon: "icons/weapons/broadblade-of-night.webp" },
    { id: "broadblade-of-voyager", name: "Broadblade of Voyager", weaponType: "Broadblade", rarity: 3, baseAtk: 300, secondaryStat: "Energy Regen", secondaryValue: 32.4, passive: "When Resonance Skill is cast, restores 8 Resonance Energy. This effect can be triggered 1 time(s) every 20s.", icon: "icons/weapons/broadblade-of-voyager.webp" },
    { id: "gauntlets-of-night", name: "Gauntlets of Night", weaponType: "Gauntlets", rarity: 3, baseAtk: 325, secondaryStat: "ATK%", secondaryValue: 24.3, passive: "When Intro Skill is cast, increases ATK by 8%, lasting for 10s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":8,"conditional":true,"autoTrigger":{"skillIds":["intro"],"durationSeconds":10}}], icon: "icons/weapons/gauntlets-of-night.webp" },
    { id: "gauntlets-of-voyager", name: "Gauntlets of Voyager", weaponType: "Gauntlets", rarity: 3, baseAtk: 325, secondaryStat: "DEF%", secondaryValue: 30.8, passive: "When Resonance Skill is cast, restores 8 Resonance Energy. This effect can be triggered 1 time(s) every 20s.", icon: "icons/weapons/gauntlets-of-voyager.webp" },
    { id: "guardian-broadblade", name: "Guardian Broadblade", weaponType: "Broadblade", rarity: 3, baseAtk: 325, secondaryStat: "ATK%", secondaryValue: 24.3, passive: "Increases Basic Attack DMG Bonus and Heavy Attack DMG Bonus by 12%.", selfBuffs: [{"stat":"dmgBonus","label":"Basic/Heavy DMG","value":12,"conditional":false,"appliesTo":["basic","heavy"]}], icon: "icons/weapons/guardian-broadblade.webp" },
    { id: "guardian-gauntlets", name: "Guardian Gauntlets", weaponType: "Gauntlets", rarity: 3, baseAtk: 300, secondaryStat: "DEF%", secondaryValue: 38.5, passive: "Increases Resonance Liberation DMG Bonus by 12%.", selfBuffs: [{"stat":"dmgBonus","label":"Liberation DMG","value":12,"conditional":false,"appliesTo":["ult"]}], icon: "icons/weapons/guardian-gauntlets.webp" },
    { id: "guardian-pistols", name: "Guardian Pistols", weaponType: "Pistols", rarity: 3, baseAtk: 300, secondaryStat: "ATK%", secondaryValue: 30.4, passive: "Resonance Skill DMG Bonus is increased by 12%.", selfBuffs: [{"stat":"dmgBonus","label":"Res. Skill DMG","value":12,"conditional":false,"appliesTo":["skill"]}], icon: "icons/weapons/guardian-pistols.webp" },
    { id: "guardian-rectifier", name: "Guardian Rectifier", weaponType: "Rectifier", rarity: 3, baseAtk: 325, secondaryStat: "ATK%", secondaryValue: 24.3, passive: "Increases Basic Attack and Heavy Attack DMG Bonus by 12%.", selfBuffs: [{"stat":"dmgBonus","label":"Basic/Heavy DMG","value":12,"conditional":false,"appliesTo":["basic","heavy"]}], icon: "icons/weapons/guardian-rectifier.webp" },
    { id: "guardian-sword", name: "Guardian Sword", weaponType: "Sword", rarity: 3, baseAtk: 300, secondaryStat: "HP%", secondaryValue: 30.4, passive: "Resonance Skill DMG Bonus is increased by 12%.", selfBuffs: [{"stat":"dmgBonus","label":"Res. Skill DMG","value":12,"conditional":false,"appliesTo":["skill"]}], icon: "icons/weapons/guardian-sword.webp" },
    { id: "originite-type-i", name: "Originite: Type I", weaponType: "Broadblade", rarity: 3, baseAtk: 300, secondaryStat: "DEF%", secondaryValue: 38.5, passive: "When Resonance Skill is cast, heals 3% of the Resonator's Max HP. This effect can be triggered 1 time(s) every 12s.", icon: "icons/weapons/originite-type-i.webp" },
    { id: "originite-type-ii", name: "Originite: Type II", weaponType: "Sword", rarity: 3, baseAtk: 325, secondaryStat: "ATK%", secondaryValue: 24.3, passive: "When Resonance Liberation is cast, heals 5% of the Resonator's Max HP. This effect can be triggered 1 time(s) every 20s.", icon: "icons/weapons/originite-type-ii.webp" },
    { id: "originite-type-iii", name: "Originite: Type III", weaponType: "Pistols", rarity: 3, baseAtk: 325, secondaryStat: "ATK%", secondaryValue: 24.3, passive: "When Dodge Counter is cast, heals 1.6% of the Resonator's Max HP. This effect can be triggered 1 time(s) every 6s.", icon: "icons/weapons/originite-type-iii.webp" },
    { id: "originite-type-iv", name: "Originite: Type IV", weaponType: "Gauntlets", rarity: 3, baseAtk: 300, secondaryStat: "CRIT DMG", secondaryValue: 40.4, passive: "When dealing Basic Attack DMG, heals 0.5% of the Resonator's Max HP. This effect can be triggered 1 time(s) every 3s.", icon: "icons/weapons/originite-type-iv.webp" },
    { id: "originite-type-v", name: "Originite: Type V", weaponType: "Rectifier", rarity: 3, baseAtk: 300, secondaryStat: "HP%", secondaryValue: 30.4, passive: "When Intro Skill is cast, heals 5% of the Resonator's Max HP. This effect can be triggered 1 time(s) every 20s.", icon: "icons/weapons/originite-type-v.webp" },
    { id: "pistols-of-night", name: "Pistols of Night", weaponType: "Pistols", rarity: 3, baseAtk: 325, secondaryStat: "ATK%", secondaryValue: 24.3, passive: "When Intro Skill is cast, increases ATK by 8%, lasting for 10s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":8,"conditional":true,"autoTrigger":{"skillIds":["intro"],"durationSeconds":10}}], icon: "icons/weapons/pistols-of-night.webp" },
    { id: "pistols-of-voyager", name: "Pistols of Voyager", weaponType: "Pistols", rarity: 3, baseAtk: 300, secondaryStat: "ATK%", secondaryValue: 30.4, passive: "When Resonance Skill is cast, restores 8 Resonance Energy. This effect can be triggered 1 time(s) every 20s.", icon: "icons/weapons/pistols-of-voyager.webp" },
    { id: "rectifier-of-night", name: "Rectifier of Night", weaponType: "Rectifier", rarity: 3, baseAtk: 325, secondaryStat: "ATK%", secondaryValue: 24.3, passive: "When Intro Skill is cast, increases ATK by 8%, lasting for 10s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":8,"conditional":true,"autoTrigger":{"skillIds":["intro"],"durationSeconds":10}}], icon: "icons/weapons/rectifier-of-night.webp" },
    { id: "rectifier-of-voyager", name: "Rectifier of Voyager", weaponType: "Rectifier", rarity: 3, baseAtk: 300, secondaryStat: "Energy Regen", secondaryValue: 32.4, passive: "When Resonance Skill is cast, restores 8 Resonance Energy. This effect can be triggered 1 time(s) every 20s.", icon: "icons/weapons/rectifier-of-voyager.webp" },
    { id: "sword-of-night", name: "Sword of Night", weaponType: "Sword", rarity: 3, baseAtk: 325, secondaryStat: "ATK%", secondaryValue: 24.3, passive: "When Intro Skill is cast, increases ATK by 8%, lasting for 10s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":8,"conditional":true,"autoTrigger":{"skillIds":["intro"],"durationSeconds":10}}], icon: "icons/weapons/sword-of-night.webp" },
    { id: "sword-of-voyager", name: "Sword of Voyager", weaponType: "Sword", rarity: 3, baseAtk: 300, secondaryStat: "Energy Regen", secondaryValue: 32.4, passive: "When Resonance Skill is cast, restores 8 Resonance Energy. This effect can be triggered 1 time(s) every 20s.", icon: "icons/weapons/sword-of-voyager.webp" },
    { id: "tyro-broadblade", name: "Tyro Broadblade", weaponType: "Broadblade", rarity: 2, baseAtk: 275, secondaryStat: "ATK%", secondaryValue: 14.8, passive: "Increases ATK by 5%.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":5,"conditional":false}], icon: "icons/weapons/tyro-broadblade.webp" },
    { id: "tyro-gauntlets", name: "Tyro Gauntlets", weaponType: "Gauntlets", rarity: 2, baseAtk: 275, secondaryStat: "ATK%", secondaryValue: 14.8, passive: "Increases ATK by 5%.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":5,"conditional":false}], icon: "icons/weapons/tyro-gauntlets.webp" },
    { id: "tyro-pistols", name: "Tyro Pistols", weaponType: "Pistols", rarity: 2, baseAtk: 275, secondaryStat: "ATK%", secondaryValue: 14.8, passive: "Increases ATK by 5%.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":5,"conditional":false}], icon: "icons/weapons/tyro-pistols.webp" },
    { id: "tyro-rectifier", name: "Tyro Rectifier", weaponType: "Rectifier", rarity: 2, baseAtk: 275, secondaryStat: "ATK%", secondaryValue: 14.8, passive: "Increases ATK by 5%.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":5,"conditional":false}], icon: "icons/weapons/tyro-rectifier.webp" },
    { id: "tyro-sword", name: "Tyro Sword", weaponType: "Sword", rarity: 2, baseAtk: 275, secondaryStat: "ATK%", secondaryValue: 14.8, passive: "Increases ATK by 5%.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":5,"conditional":false}], icon: "icons/weapons/tyro-sword.webp" },
    { id: "training-broadblade", name: "Training Broadblade", weaponType: "Broadblade", rarity: 1, baseAtk: 250, secondaryStat: "ATK%", secondaryValue: 11.5, passive: "Increases ATK by 4%.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":4,"conditional":false}], icon: "icons/weapons/training-broadblade.webp" },
    { id: "training-gauntlets", name: "Training Gauntlets", weaponType: "Gauntlets", rarity: 1, baseAtk: 250, secondaryStat: "ATK%", secondaryValue: 11.5, passive: "Increases ATK by 4%.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":4,"conditional":false}], icon: "icons/weapons/training-gauntlets.webp" },
    { id: "training-pistols", name: "Training Pistols", weaponType: "Pistols", rarity: 1, baseAtk: 250, secondaryStat: "ATK%", secondaryValue: 11.5, passive: "Increases ATK by 4%.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":4,"conditional":false}], icon: "icons/weapons/training-pistols.webp" },
    { id: "training-rectifier", name: "Training Rectifier", weaponType: "Rectifier", rarity: 1, baseAtk: 250, secondaryStat: "ATK%", secondaryValue: 11.5, passive: "Increases ATK by 4%.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":4,"conditional":false}], icon: "icons/weapons/training-rectifier.webp" },
    { id: "training-sword", name: "Training Sword", weaponType: "Sword", rarity: 1, baseAtk: 250, secondaryStat: "ATK%", secondaryValue: 11.5, passive: "Increases ATK by 4%.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":4,"conditional":false}], icon: "icons/weapons/training-sword.webp" },
    // 8 5★ weapons added 2026-07-12 — the live roster had 120, this catalog had
    // only 112; sourced from api.encore.moe/en/weapon/{id}, cross-verified
    // against wuthering.gg (passive text matched verbatim on 2 spot-checked
    // entries — see [[ww-second-source-recheck]]).
    { id: "solsworn-ciphers", name: "Solsworn Ciphers", weaponType: "Gauntlets", rarity: 5, baseAtk: 588, secondaryStat: "CRIT DMG", secondaryValue: 48.6, passive: "Increases ATK by 12%. Casting Intro Skill or Echo Skill grants 32% Echo Skill DMG Amplification for 15s. When dealing Echo Skill DMG, Aero DMG ignores 10% of the target's DEF for 6s.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false}], icon: "icons/weapons/solsworn-ciphers.webp" },
    { id: "forged-dwarf-star", name: "Forged Dwarf Star", weaponType: "Rectifier", rarity: 5, baseAtk: 500, secondaryStat: "CRIT Rate", secondaryValue: 36, passive: "Increases ATK by 12%. After the wielder inflicts Fusion Burst or Tune Strain - Shifting on the target, their Resonance Liberation DMG Bonus is increased by 36% for 5s. While this effect lasts, after Resonators in the team inflict Fusion Burst or Tune Strain - Shifting, their ATK is increased by 24% for 15s. Effects of the same name cannot be stacked.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Liberation DMG","value":36,"conditional":true,"appliesTo":["ult"]}], icon: "icons/weapons/forged-dwarf-star.webp" },
    { id: "frostburn", name: "Frostburn", weaponType: "Sword", rarity: 5, baseAtk: 588, secondaryStat: "CRIT Rate", secondaryValue: 24.3, passive: "ATK is increased by 12%. After the wielder applies Glacio Chafe, Glacio DMG is Amplified by 28%, and Resonance Liberation DMG ignores 10% of the target's DEF. If the wielder is the active Resonator in the team, Glacio Chafe DMG dealt to all targets within a certain range is Amplified by 20% for 6s. This effect can be triggered up to 1 times every 0.1s. Only the strongest effect of the same name applies.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false}], icon: "icons/weapons/frostburn.webp" },
    { id: "spectral-trigger", name: "Spectral Trigger", weaponType: "Pistols", rarity: 5, baseAtk: 588, secondaryStat: "CRIT DMG", secondaryValue: 48.6, passive: "Increases ATK by 12%. Casting Resonance Skill grants 20% Spectro DMG Bonus to the wielder for 14s, stacking up to 2 times. Inflicting Hack - Shifting grants 30% Heavy Attack DMG Amplification to the wielder for 14s, during which Heavy Attack DMG ignores 10% of the target's DEF.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"elemDmg","label":"Elem DMG","value":20,"conditional":true},{"stat":"dmgBonus","label":"Heavy DMG","value":30,"conditional":true,"appliesTo":["heavy"]},{"stat":"defIgnore","label":"DEF Ignore (Heavy Atk)","value":10,"conditional":true,"appliesTo":["heavy"]}], icon: "icons/weapons/spectral-trigger.webp" },
    { id: "skull-thrasher", name: "Skull Thrasher", weaponType: "Pistols", rarity: 5, baseAtk: 500, secondaryStat: "CRIT DMG", secondaryValue: 72, passive: "Increases ATK by 12%. Casting Intro Skill grants 24% Basic Attack DMG Bonus to the wielder for 14s. Inflicting Hack - Shifting grants 12% Basic Attack DMG Bonus to the wielder for 14s, and increases the ATK of Resonators in the team by 24% for 30s. Effects of the same name do not stack.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"dmgBonus","label":"Basic DMG","value":24,"conditional":true,"appliesTo":["basic"],"autoTrigger":{"skillIds":["intro"],"durationSeconds":14}}], icon: "icons/weapons/skull-thrasher.webp" },
    { id: "freeze-frame", name: "Freeze Frame", weaponType: "Rectifier", rarity: 5, baseAtk: 588, secondaryStat: "CRIT Rate", secondaryValue: 24.3, passive: "Increases ATK by 12%. After inflicting Glacio Chafe on the target, the wielder gains 30% Glacio DMG Bonus for 12s, and all Resonators in the team gain 24% ATK increase for 30s. Effects of the same name cannot be stacked.", selfBuffs: [{"stat":"atkPct","label":"ATK%","value":12,"conditional":false},{"stat":"elemDmg","label":"Elem DMG","value":30,"conditional":true}], icon: "icons/weapons/freeze-frame.webp" },
    { id: "azure-oath", name: "Azure Oath", weaponType: "Sword", rarity: 5, baseAtk: 588, secondaryStat: "CRIT Rate", secondaryValue: 24.3, passive: "Grants 12% All-Attribute DMG Bonus. After inflicting Havoc Bane, the wielder gains 36% Heavy Attack DMG Amplification and their Heavy Attack DMG ignores 12% of the target's DEF, lasting for 8s.", selfBuffs: [{"stat":"elemDmg","label":"DMG Bonus","value":12,"conditional":false},{"stat":"dmgBonus","label":"Heavy DMG","value":36,"conditional":true,"appliesTo":["heavy"]}], icon: "icons/weapons/azure-oath.webp" },
    { id: "firstlights-herald", name: "Firstlight's Herald", weaponType: "Rectifier", rarity: 5, baseAtk: 413, secondaryStat: "Energy Regen", secondaryValue: 77.04, passive: "Increases Max HP by 12%. Casting Resonance Liberation restores 8 points of Concerto Energy, triggered once every 20s. Inflicting Glacio Chafe grants Snow Taint for 6s. Applying healing grants Ripples for 6s. If the wielder has done both while on the field, the next Outro Skill grants both effects for 6s. When the wielder has both Snow Taint and Ripples, the ATK of all nearby Resonators in the team is increased by 20%. Effects of the same name do not stack.", selfBuffs: [{"stat":"hpPct","label":"HP%","value":12,"conditional":false}], icon: "icons/weapons/firstlights-herald.webp" },
];

export const getWeapon = (id: string): WUWeapon | undefined => WEAPONS.find((w) => w.id === id);
